### ISSUE TITLE
아이템 16. public 클래스에서는 public 필드가 아닌 접근자 메서드를 사용하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#16]

**Comment by luckyDaveKim** [comment]
## public 클래스에서는 public 필드가 아닌 접근자 메서드를 사용

### Do Not
- 데이터 필드에 직접 접근할 수 있으니, 캡슐화의 이점을 제공하지 못함
- API 수정 없이는 내부 표현을 바꿀 수 없음
- 불젼식을 보장할 수 없음
- 외부에서 필드 접근 시 부수적인 작업을 할 수 없음
```java
public class Point {
	public double x;
	public double y;
}
```

### Do
- 필드를 모두 private 로 만들고, public 접근자를 제공
```java
public class ImprovedPoint {
	private double x;
	private double y;

	public ImprovedPoint(double x, double y) {
		this.x = x;
		this.y = y;
	}

	public double getX() {
		return x;
	}

	public void setX(double x) {
		this.x = x;
	}

	public double getY() {
		return y;
	}

	public void setY(double y) {
		this.y = y;
	}
}
```

## 마무리
- public 클래스는 절대 가변 필드를 직접 노출하면 안된다.
- 불변 필드는 노출해도 위험이 적지만, 완전히 안심할 수 없으며 API를 변경하지 않고는 표현 방식을 바꿀 수 없다.
- package-private 클래스, private 중첩 클래스는 필드를 노출하는 편이 나을 때도 있다.
