### ISSUE TITLE
아이템 17. 변경 가능성을 최소화하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#17]

**Comment by luckyDaveKim** [comment]
## 클래스를 불변으로 만드는 5가지 규칙
- 객체의 상태를 변경하는 메서드를 제공하지 않는다.
- 클래스를 확장할 수 없도록 한다.
- 모든 필드를 final로 선언한다.
- 모든 필드를 private으로 선언한다.
- 자신 외에는 내부의 가변 컴포넌트에 접근할 수 없도록 한다.

> Tip : 불변 클래스의 메서드는 동사(add) 대신 전치사(plus)를 사용  
> 이는 해당 메서드가 객체의 값을 변경하지 않는다는 사실을 강조


## 불변 클래스
ex: String, BigInteger, BigDecimal 등...

```java
public final class Complex {
	private final double re;
	private final double im;

	public Complex(double re, double im) {
		this.re = re;
		this.im = im;
	}

	public double realPart() {
		return re;
	}

	public double ImaginaryPart() {
		return im;
	}

	// 1. 동사(add) 가 아닌, 전치사(plus) 사용하여, 이 메서드가 객체의 값을 변환하지 않음을 강조
	// 2. 객체 자신을 수정하지 않고, 새로운 Complex 인스턴스를 만들어 반환
	public Complex plus(Complex o) {
		return new Complex(re + o.re, im + o.im);
	}

	public Complex minus(Complex o) {
		return new Complex(re - o.re, im - o.im);
	}

	public Complex times(Complex o) {
		return new Complex(re * o.re - im * o.im, re * o.im + im * o.re);

	}

	public Complex dividedBy(Complex o) {
		double tmp = o.re * o.re + o.im + o.im;
		return new Complex((re * o.re + im * o.im) / tmp, (im * o.re - re * o.im) / tmp);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;
		Complex complex = (Complex)o;
		return Double.compare(complex.re, re) == 0 && Double.compare(complex.im, im) == 0;
	}

	@Override
	public int hashCode() {
		return Objects.hash(re, im);
	}

	@Override
	public String toString() {
		return String.format("(%f + %fi)", re, im);
	}
}
```

### 장점
- thread safe하여 별도의 동기화 로직 불필요
  (안심하고 공유 가능)
- 계산 비용이 큰 메소드 결과는 캐싱해두고 재사용 가능
  (불변 클래스이기에 가능한 묘수)

### 단점
- 값이 다르면 반드시 독립된 객체로 만들어야 함
  (생성 비용이 큰 객체의 경우 오버헤드가 큼)

> 단점 극복 : 가변 동반 클래스 제공 
> ex: StringBuilder 등...

### 불변 클래스 만드는법
-  final 클래스로 선언
- 모든 생성자를 private, package-private로 선언 후, public 정적 팩터리 제공
  (장점1 : 패키지 내부에서는 자유롭게 활용하며, 패키지 밖에서는 생성자 접근이 안되어 확장이 불가)
  (장점2 : 정적 팩터리 방식은 객체 캐싱 기능을 제공 가능)


> 직렬화 주의점
> `Serializable`을 구현하는 불변 클래스의 내부에 가변 객체를 참조하는 필드가 있다면,
> `readObject`, `readResolve` 메서드를 정의해야한다
> 참고 : https://github.com/NMP-Study/EffectiveJava2022/blob/4be6aa4df8e807ee7814eeb7c84d83aa417aedb5/src/main/java/org/effectivejava/item17/MutableAttack.java#L5


## 마무리
- 클래스는 꼭 필요한 경우가 아니라면 불변이어야 한다.
- 불변으로 만들 수 없는 클래스라도 변경할 수 있는 부분을 최소한으로 줄이다.
- 다른 합당한 이유가 없아면 모든 필드는 private final이어야 한다.
- 생성자는 불변식 설정이 모두 완료된, 초기화가 완벽히 끝난 상태의 객체를 생성해야 한다.
