### ISSUE TITLE
아이템 20. 추상 클래스보다는 인터페이스를 우선하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#20]

**Comment by windowforsun** [comment]
### 요약
- 추상클 래스보다 자유로운 인터페이스를 사용하자.
- `Java 8` 부터 활용할 수 있는 `default method` 를 사용하면 추상 클래스처럼 구현에 도움을 줄 수 있다. 
- 인터페이스의 구현상 제약이 있는 경우 추상 클래스와 함께 골격 구현을 사용하자.

### 기존 클래스에도 쉽게 인터페이스를 구현해 넣을 수 있다. 

```java
public class FooClass {
    public void methodA() {
        // do something ..
    }
}

public class BarClass {
    public void methodB() {
        // do something ..
    }
}

public class FooBarClass {
    public void methodA() {
        // do something ..
    }
    
    public void methodB() {
        // do something ..
    }
}
```  

위 처럼 `methodA` 를 함께 사용하는 2개의 클래스에 인터페이스를 구현해 넣는다면 아래와 같이 선언된 메소드들을 인터페이스에 정의해 주기만 하면 된다. 

```java
public interface Foo {
    void methodA();
}

public interface Bar {
    void methodB();
}

// 간편하게 기존 인터페이스 확장 가능
public interface FooBar extends Foo, bar {
    
}

public class FooClass implements Foo {}
public class BarClass implements Bar {}
// 혹은 Foo, Bar 각각 구현 하는 것도 가능
public class FooBarClass implements Foo, Bar {}
```  

만약 추상 클래스를 사용한다면 단일 상속과 계층적 구조로 인해 적잘히지 않은 계층 구조를 가지게되면서 혼란을 불어일으킨다. 

```java
public abstract class Foo {
    abstract void methodA();
}

// 확장을 위해 적절치 않은 구조와 강제성이 있는 상속이 이뤄짐
public abstract class Bar extends Foo {
    abstract void methodB();
}

public class FooClass extends Foo {}
public class BarClass extends Bar {}
public class FooBarClass extends Bar {}
```  

### 인터페이스는 믹스인(mixin) 정의에 안성맞춤이다. 
믹스인은 대상 클래스의 주된 기능에 선택적 이상을 혼합하는 것을 의미한다. 
아래와 같은 이미 상속중인 클래스가 있다고 가정해보자. 

```java
public class MyModel extends CommonModel {
    
}
```  

순서 지정을 기능을 제공하는 `Comparable` 이 인터페이스인 경우 아래와 같이 `mixin` 할 수 있다. 
인터페이스를 통해 원하는 만큼 선택적 기능들을 `mixin` 할 수 있다. 

```java
public class MyModel extends CommonModel implements Comparble {
    
}
```  

하지만 만약 순서 지정 기능을 제공하는 `Comparable` 이 추상 클래스 였다면 ? 

```java
public abstract class Comparable {}

// ??????????????? 불가능
public class MyModel extends CommonModel, Comparable {
    
} 
```  

문법적으로 클래스 계층구조를 갖는 추상 클래스에서는 불가능 하다. 



### 계층구조가 없는 타입 프레임워크 구현 가능
계층적인 구조를 잘 활용하면 다양한 개념들을 구조적으로 표현할 수 있다. 
하지만 현실에는 표현하기 어려운 예외적인 개념도 존재한다. 가수와 작곡가 있을 때 작곡하는 가수도 현실에는 존재한다.  

먼저 인터페이스로 구현해보면 별다른 어려움 없이 간단하게 가능하다. 

```java
public interface Singer {
    Audio sing(Song s);
}

public interface SongWriter {
    Song compose(int chartPosition);
}

public class SingSong implements Singer, SongWriter {
    
}
```  

혹은 아래 확장과 동시에 새로운 메소드까지 추가할 수 있다. 

```java
public interface SingerSongWriter extends Singer, SongWriter {
    Audio strum();
    void actSensitive();
}
```  

만약 추상 클래스를 사용한다면 현실 개념과는 맞지 않은 포함관계를 만들거나, 독립된 형태로 구성해야 한다. 

```java
public abstract class Singer {
    abstract Audio sing(Song s);
}

// 작곡가는 무조건 가수여야 한다 ?
public abstract class SongWriter extends Singer {
    abstract Song compose(int chartPosition);
}

// 혹은 아예 따로 만들어 버린다. 
public abstract class SingerSongWriter {
    abstract Audio sing(Song s);
    abstract Song compose(int chartPosition);
}
```  


### 래퍼 클래스와 인터페이스의 조합은 기능확장에 안전하고 강력하다. 
인터페이스로 정의하게 될 경우 다중 구현을 통해 계속적인 기능 확장이 가능하다. 
하지만 추상 클래스를 사용하게 되면 기능 확장은 상속 뿐이므로 활용도가 떨어지고 관계가 깨지기 쉽다.  

```java
public class ForwardingSet<E> implements Set<E>, SortedSet<E>,  NavigableSet<E>{
    private final Set<E> s;
    public ForwardingSet(Set<E> s) { this.s= s;}

    public void clear() {s.clear();}
    public boolean contains(Object o) { return s.contains(o);}
    
    // ...

}
```  

### 인터페이스 디폴트 메서드
인터페이스 메서드 중 구현방법이 명확한 것이 있다면 디폴트 메서드로 제공할 수 있다. 

```java
public interface Foo {
    default void methodA() {
        // do some
    }
    
    public static void methodB() {
        // do some
    }
    
    private static void methodC() {
        // do some
    }
}
```  

- 단, default 메서드를 제공할 때 상속하는 사람들을 위한 설명을 @implSpec 자바독 태그를 붙여 문서화가 필요하다. 
- equals나 hashCode 같은 Object 메서드를 디폴트 메서드로 제공해서는 안된다.
- 인터페이스는 인스턴스 필드를 가질 수 없고, public이 아닌 정적 맴버도 가질 수 없다(자바 9부터는 private static 메서드도 구현가능) 


### 추상 골격 구현(skeletal implementation)
`추상 골격 구현` 을 사용하면 인터페이스와 추상 클래스의 장점을 모두 취할 수 있다. 
이는 `템플릿 메소드 패턴` 이라고도 한다.  

특징은 아래와 같다. 
- 이름 규칙 `Abastract<인터페이스이름>`
  - `AbstractList`, `AbastractSet`
- `Collection`, `List`, `Set` 인터페이스를 구현하는 것보다, 골격 구현 클래스인 `AbstractList`, `AbstractSet` 를 사용하는 것이 훨씬 편하다. 
- 구조상 골격 구현을 확장하기 어렵다면, 인터페이스를 직접 구현해야 한다. 
- 위 방법을 사용하거나 #18  래퍼 클래스와 비슷한 방법으로 시뮬레이트한 다중 상속(simulated multiple inheritance) 를 사용할 수 있다. 



1. 인터페이스에서 다른 구현에 사용되는 기반 메서드를 선정한다.  

```java
public interface List<E> extends Collection<E> {
    void add(int index, E element);
    boolean add(E e);
    boolean isEmpty();
    int size();
    Object[] toArray();
    void sort(Comparator<? super E> c);
}
```  

2. 기반 메서드를 사용해서 직접 구현가능한 메서드는 모두 디폴트 메서드로 구현한다. 

```java
public interface List<E> extends Collection<E> {
    void add(int index, E element);
    boolean add(E e);
    boolean isEmpty();
    int size();
    
    // 기반 메서드
    Object[] toArray();
    
    // 기반 메서드 사용
    default void sort(Comparator<? super E> c) {
        Object[] a = this.toArray();
        Arrays.sort(a, (Comparator) c);
        ListIterator<E> i = this.listIterator();
        for (Object e : a) {
            i.next();
            i.set((E) e);
        }
    }
}
```  

3. 기반 메서드나 디폴트 메서드로 만들지 못한 메서드는 인터페이스를 구현하는 골격 클래스(추상 클래스) 만들어 남은 메서드를 작성한다. 필요한 경우 `public` 이 아닌 필드와 메서드도 추가할 수 있다.  

```java
public abstract class AbstractList<E> extends AbstractCollection<E> implements List<E> {
    // 반드시 재정의 해야 한다. 
    public void add(int index, E element) {
        throw new UnsupportedOperationException();
    }

    // 일반규약 구현
    public boolean add(E e) {
        add(size(), e);
        return true;
    }

    // 일반규약 구현
    public boolean isEmpty() {
        return size() == 0;
    }

    // 완전한 기반 메서드
    public abstract int size();
}
```  

4. 골격 구현은 기본적으로 상속해서 사용하는 것이기 때문에 설계 및 문서화 지침을 모두 따랴야 한다. (#19 )


### 단순 구현(Simple implementation)
- 골격 구현의 작은 변종으로, 쉽게 말하자면 '동작하는 가장 단순한 구현' 이라고 한다. 
- 상속을 위해 인터페이스를 구현한 건 같지만, 추상 클래스가 아니란 점이 골격 구현과 다르다. 
- 간단하게 인터페이스를 모두 다 구현한 구현 클래스라고 할 수 있다.

**Comment by bluewbear** [comment]
@qlqhqo2341 님이 찾으신 default method 설명 : http://kbs0327.github.io/blog/technology/java8-default-interface/
