### ISSUE TITLE
아이템 21. 인터페이스는 구현하는 쪽을 생각해 설계하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#21]

**Comment by qlqhqo2341** [comment]
## 인터페이스는 구현하는 쪽을 생각해 설계하라
#### 시간이 지나면서 기존 인터페이스에 메소드가 추가해야 하면 어떻게 해야할까?
- 기존 구현체를 모두 깨야함.
- JAVA 8에 와서야 인터페이스에 디폴트 메소드를 추가할 수 있게 되었음.
	- 람다기능의 추가로 컬렉션 인터페이스에서 활용하기 위해 추가됨.
- 대표적으로 java의 `Collection` 인터페이스에 디폴트 메소드가 추가됨.
```java
default boolean removeIf(Predicate<? super E> filter) {  
    Objects.requireNonNull(filter);  
    boolean result = false;  
    for (Iterator<E> it = iterator();it.hasNext();) {
        if (filter.test(it.next())) {  
            it.remove();  
            result = true;  
        }
    } 
    return result;  
}
```
- 코드 자체가 범용적이나 모든 `Collection` 구현체와 잘 어우러지는 것은 아님.
- 예시) 아파치의 `SynchronizedCollection`
	- 위에서 정의한 java 8의 `removeIf` 디폴트 구현으로는, 아파치의 락 객체를 모르므로 사용할 수 없음.
	- 동기화가 되지 못하고 위험한 결과가 생길 수 있음.
- 자바에서도 필요한 부분에서는 디폴트 메소드 재정의를 진행함.
	- 자바의 `SyunchronizedCollection`은 `removeIf`를 재정의하고 있음.
```java
@Override  
public boolean removeIf(Predicate<? super E> filter) {  
    synchronized (mutex) {return c.removeIf(filter);}  
}
```

> 아파치 `SynchronizedCollection`의 `removeIf` 재정의도 아파치 4.4부터 추가된 것으로 보인다.
> 새로운 구현도 위와 자바의 방법과 거의 똑같은 방법을 사용하고 있음.
> https://github.com/apache/commons-collections/blob/master/src/main/java/org/apache/commons/collections4/collection/SynchronizedCollection.java#L183


#### 인터페이스를 설계할때는 주의를 기울여서 설계하자
- 추 후에 디폴트 메서드 추가는
	- 꼭 필요한 일이 아니면 피해야 함.
	- 기존 구현체와 충돌 가능성이 없는지 확인해야함.
- 새로운 인터페이스를 만들 때에는, 표준적인 구현을 제공하며, 쉽게 활용할 수 있도록 해줌 #20
- 새로운 인터페이스를 설계할 때는, 릴리즈 전에 반드시 테스트를 거치자
	- 릴리즈 전에 적어도 3가지 이상의 다른 방식으로 구현볼것
	- 만든 각 인스턴스를 다양한 작업에 사용해볼것
- **인터페이스를 릴리즈한 뒤라도 결함을 수정하는 것이 가능할 수 있겠지만, 그 가능성에 기대면 안됨.**
