### ISSUE TITLE
아이템 26. 로 타입은 사용하지 말라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#26]

**Comment by bluewbear** [comment]
## 로 타입(Raw Type)은 사용하지 말라

### 용어 정리

- 제네릭 클래스 혹은 제네릭 인터페이스
  - 클래스/인터페이스 선언에 타입 매개변수(type parameter)가 쓰이는 경우
  - 제네릭 타입이라 한다.
- 클래스(혹은 인터페이스) 이름이 나오고 <> 안에 실제 타입 매개변수를 나열
  - `List<String>`
- 제네릭 타입을 정의하면 로 타입도 함께 정의
  - 로 타입 Raw Type이란?
    - 제네릭 타입에서 타입 매개변수를 전혀 사용하지 않는 것
  - 제네릭 타입 : `List<String>`, 로 타입 : `List`
  - 제네릭 개념을 도입하기 전 하위 버젼 호환을 위한 궁여지책

### 로 타입 사용~

- EX) 컬렉션의 로 타입 
  - ```java
     // Stamp 인스턴스만 취급
     private final Collection stamps = ....;
    ```
  - Stamp 대신 Coin 객체를 집어넣어도 아무런 문제 없이 컴파일도 되고 실행도 된다
  - ```java
     stamps.add(new Coin()); // OMG "unchecked call" 경고 발사 
    ```
  - ```java
     for (Iterator i = stamps.iterator() ; i.hasNext(); ) {
         Stamp stamp = (Stamp) i.next(); // OMG ClassCaseException 발사
         ....
     }
    ```
- 제네릭을 활용하면?
  - ```java
     private final Collection<Stamp> stamps = ... ;
    ```
  - 타입 안정성 확보!
  - 컴파일 오류도 없고(경고도 없고!), 의도대로 `Stamp`만 취급
  - `Coin`을 넣는다고 하면..
    - <img width="450" alt="스크린샷 2022-09-07 오전 12 09 22" src="https://user-images.githubusercontent.com/18572514/188671072-2d3b38bb-1b0a-4362-b4ec-8f4d80ca49a6.png">
    - 인텔리제이도 빨간불, 컴파일 후 오류 메세지 툭.
- **로 타입을 쓰는 것을 언저 차원에서 막아 놓지는 않았지만 절대로 사용금지**
  - 제네릭이 보장하는 안전성, 표현력을 사용할 수 없다. 
- `List<Object>` 와 같이 임의 객체를 허용하는 경우는 괜찮다... 읭??
- 컴파일러에게 명확하게 전달!

`List` | `List<Object>`
--|-- 
제네릭을 완전 무시 | 모든 타입을 다 허용한다는 의미 

- `List`를 받는 method에 `List<String>` 전달 가능하지만, `List<Object>`를 받는 method에는 안된다.
  - 제네릭의 하위 타입 규칙 
- <img width="500" alt="스크린샷 2022-09-07 오전 12 19 08" src="https://user-images.githubusercontent.com/18572514/188673766-c9dcada4-4de6-4546-a865-c98665167914.png">

  - 코드상에도 문제가 없어 보이고, 컴파일에도 오류가 없다.
  - _책에는 경고가 나타난다는데... 내 로컬에서는 경고가 안 보임 ;;_
  - 하지만, 실행하면 Runtime으로 오류 발생 
- <img width="500" alt="스크린샷 2022-09-07 오전 12 30 58" src="https://user-images.githubusercontent.com/18572514/188675755-2b9b32d4-5434-4ffe-af81-962211555cae.png">

  - 인텔리제이 빨간불 들어오고, 컴파일해도 오류 발생하고 @.,@

### BUT, 난 원소의 타입 따윈 알고 싶지 않다~

- EX) 모르는 타입의 원소도 받고 싶다!
  - ```java
     public int numElementsInCommon(Set s1, Set s2) {
          int result = 0;
          for (Object o1 : s1) {
              if (s2.contains(o1)) {
                  result++;
              }
          }
          return result;
      }
      ```
  - 동작 가능하지만 로타입을 사용했기에 안전하지 않다.
- 비한정적 와일드 카드 타입 (unbounded wildcard type)을 대신 사용!
  - 제네릭은 쓰고는 싶은데, 실제 타입은 뭔지 신경끄고 싶을때 물음표(?)를 사용 
  - 제네릭 타입 : `Set<E>` , 비한정적 와일드카드 타입 : `Set<?>`
  - 이것이야말로 어떤 타입이라도 담을 수 있는 가장 범용적인 매개변수화 Set 타입!
  - ```java
     public int numElementsInCommon(Set<?> s1, Set<?> s2) {
         ..
     }
     ```
- `Set<?>`와 `Set`의 차이는?
  - 안전하냐 안하냐의 차이 
- 로 타입은 아무 원소나 넣을 수 있으니 타입 불변식을 훼손할 수 있다.
  - `Collection<?>` 에는 어떤 원소도 넣을 수 없다.
  - 뭔가 넣으려고 하면 컴파일 오류 발생 
  - 어쨌든 컴파일러는 제 역할을 수행함 
  - [oracle이 알려주는 Unbounded Wildcards에 대한 이야기](https://docs.oracle.com/javase/tutorial/java/generics/unboundedWildcards.html)
    - ```html
       It's important to note that List<Object> and List<?> are not the same. 
       You can insert an Object, or any subtype of Object, into a List<Object>. 
       But you can only insert null into a List<?>. 
       ```
    - https://stackoverflow.com/a/35273095
  - [oracle이 알려주는 Wildcard 사용 가이드라인](https://docs.oracle.com/javase/tutorial/java/generics/wildcardGuidelines.html)

### 그럼에도 불구하고 로 타입을 써야하는 소소한~ 예외

- 제네릭은 구체화가 되지 않은 타입!
- class 리터럴에는 로 타입을 사용
  - ```java
     // 돼~
     List.class
     String[].class
     int.class
     // 안돼~
     List<String>.class
     List<?>.class
    ```
- `instanceof` 연산자 
  - 런타임에는 제네릭 타입 정보가 지워지므로, 비한정적 와일드카드 타입 이외의 매개변수화 타입에는 적용 불가 
  - 로 타입이든 비한정적 와일드카드 타입이든 `instanceof`는 똑같이 동작 
  - EX) 올바른 예
    - ```java
       if (o instanceof Set) {
             Set<?> s = (Set<?>) o;
             ...
       }
      ```

### 핵심정리

- 로 타입을 사용하면 런타임시 예외 발생하니 사용 금지
- `Set<Object>` 는 어떤 타입의 객체도 저장할 수 있는 매개변수화 타입
- `Set<?>` 는 모종의 타입 객체만 저장할 수 있는 와일드카드 타입 
- `Set<Object>`, `Set<?>`는 안전하지만 로 타입 Set은 안전하지 않다.

### 부록

한글 | 영문 | 예 | 아이템
--|--|--|--
매개변수화 타입 | parameterized type | `List<String>` | Item26
실제 타입 매개변수 | actual type parameter | `String` | Item26
제네릭 타입 | generic type | `List<E>` | Item26,29
정규 타입 매개변수 | formal type parameter | `E` | Item26
비한정적 와일드카드 타입 | unbounded wildcard type | `List<?>` | Item26
로 타입 | raw type | `List` | Item26
한정적 타입 매개변수 | bounded type parameter | `<E extends Number>` | Item29
재귀적 타입 한정 | recursive type bound | `<T extends Comparable<T>>` | Item30
한정적 와일드카드 타입 | bounded wilecard type | `List<? extends Number>` | Item31
제네릭 메서드 | generic method | `static <E> List<E> asList(E[] a)` | Item30
타입 토큰 | type token | `String.class` | Item33

### 참고

- [What is a raw type?](https://stackoverflow.com/a/2770692)

**Comment by KimYunsang-v** [comment]
### Collection<?> 에는 어떤 원소도 넣을 수 없다.
<img width="615" alt="스크린샷 2022-09-07 오후 2 22 35" src="https://user-images.githubusercontent.com/26866812/188795411-e2a98231-e462-4976-9b3d-8acdaec923b6.png">

요건 위에서 설명주셨던대로 `?`은 `Object`의 하위타입이 아닌 별도의 type(unkown type) 이므로 null 이 아닌 객체는 `?`로 캐스팅할 수 없어 `add` 메소드 호출이 불가능한듯합니다.

컴파일 시 변경 불가능한 collection으로 바뀌거나 하는게 아니네요 ㅎㅎ

```html
It's important to note that List<Object> and List<?> are not the same. 
You can insert an Object, or any subtype of Object, into a List<Object>. 
 But you can only insert null into a List<?>. 
```

제가 잘못이해했다면 말씀 부탁드립니다~
