### ISSUE TITLE
아이템 30. 이왕이면 제네릭 메서드로 만들라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#30]

**Comment by qlqhqo2341** [comment]
# 이왕이면 제너릭 메서드로 만들라
- 메서드도 제너릭으로 만들 수 있다.
- 정적 유틸리티 메서드가 보통 제너릭 메서드로 만들어져있다.

## 아래 메서드를 제너릭으로 만들어보자.

```java
public static Set union(Set s1, Set s2) {
	set result = new hashSet(s1); // 경고!
	result.addAll(s2); // 경고!
	return result;
}
```
컴파일은 되지만, 위의 두 라인에서 unchecked call 경고가 뜬다.

- 제너릭 메서드로 만들기 위해, 타입 매개변수 목록을 제한자와 반환타입 사이에 추가한다.
```java
public static <E> Set<E> union(Set<E> s1, Set<E> s2) {
	Set<E> result = new HashSet<>(s1);
	result.addAll(s2);
	return result;
}


// 아래와 같이 사용할 수 있다.
public static void main(String[] args) {
	Set<String> guys = Set.of("톰", "딕", "해리");
	Set<String> stooges = Set.of("래리" ,"모에", "컬리");
	Set<String> aflCio = union(guys, stooges);
	System.out.println(aflCio);
}
```
- 여기에서 만든 union  함수는 입력 2개, 반환 1개의 타입이 모두 같아야 하는 문제가 있음.
	- #31 을 이용해 더 유연하게 만들 수 있음.

## 제너릭 싱글턴 팩터리
- 때때로 하나의 불변 객체를 여러 타입으로 활용 해야할 필요가 있다.
- 제너릭은 런타임에 타입정보가 소거되므로, 어떤 타입으로든 매개변수화 할 수 있다.
	- 이렇게 바꿔주는 것을 **제너릭 싱글턴 팩터리** 라고한다.
- 예시)
	- `Collections.reverseOrder` (#42)
	- `Collections.emptySet`

### 항등 함수를 한번 구현해보자.
- 자바 라이브러리에는 이미 구현되있음 `Functions.identity`
- 항등 함수객체는 상태가 없으니, 계속 객체를 만들필요가 없음.
```java
private static UnaryOperator<Object> IDENTITY_FN = (t) -> t;

@SuppressWarnings("unchecked")
public static <T> UnaryOperator<T> identityFunction() {
	return (UnaryOperator<T>) IDNEITTY_FN;
}
```
- `IDNEITTY_FN` 을 `UnaryOperator<T>`로 형변환하면 비검사 형변환 경고가 발생하지만, (`UnaryOperator<Object>`는 `UnaryOperator<T>`가 아니기 때문) 로직상, 입력값을 그대로 반환하므로, 타입 안전.
- 이 사실을 알고 있으니,  `@SuppressWarnings("unchecked")`를 추가해서 경고를 숨김.
> openjdk의 Collections.emptySet도 비슷하게 구현되있음 [코드링크](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/Collections.java#L4422)

## 재귀적 타입 한정
- 자기 자신이 들어간 표현식을 사용하여 타입 매개변수의 허용 범위를 한정 할 수 있다.
- 예를 들어 `Comparable`의 경우 아래와 같이 정의되고..
```java
public interface Comparable<T> {
	int compareTo(T o);
}
```
- 타입 매개변수 T는 `Comparable<T>`를 구현한 타입이 비교할 수 있는 타입을 정의.
- 거의 모든 타입이 자기 자신과 비교할 수 있는 타입이다.
	- `String`은 `Comparable<String>`을 구현
	- `Integer`는 `Comparable<Integer>`를 구현
- 컬렉션에서 max, min과 같은 함수를 구현하려면, 비교 가능한 타입이어야 함!
	- 아래처럼 재귀적 타입한정을 사용해서, `Comparable<E>`를 구현한 타입만 사용하도록 제한가능.
```java
// extends 구문을 사용하여 받을 수 있는 타입을 한정함.
public static <E extends Comparable<E>> E max(Collection<E> c) {
	if (c.isEmpty())
		throw new IllegalArgumentException("컬렉션이 비어있습니다.");
	E result = null;
	for (E e : c)
		if (result == null || e.compareTo(result) > 0)
			result = Objects.requireNonNull(e);
	return result;
}
```
- 재귀적 타입 한정을 사용하면 훨씬 복잡해질 가능성이 있으나, 그런 일이 많지 않음.

## 정리
- 형변환보다 제너릭이 안전하고 사용하기에 쉬우니, 제너릭 메서드로 만들자.
