### ISSUE TITLE
아이템 32. 제네릭과 가변인수를 함께 쓸 때는 신중하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#32]

**Comment by KimYunsang-v** [comment]
- 가변인수 (varargs)
  - 제네릭과 함께 자바5에 추가됨
  - 메서드에 넘기는 인수의 개수를 클라언트가 조절할 수 있게 해줌
```java 
public String formatWithVarArgs(String... values) {
    // ...
}
```

### 가변인수는 제네릭과 궁합이 좋지 않다.
- 가변인수 메서드를 호출하면 가변인수를 담기 위한 배열이 자동으로 생성되는데 이 배열을 클라이언트에게 노출 시킴 
- 만약 가변인수로 실체화 불가 타입(제네릭, 매개변수화 타입)을 받는다면 힙오염이 발생할 수 있음
```java
static void dangerous(List<String>... stringLists) {
	List<Integer> intList = List.of(42);
	Object[] objects = stringLists;
	objects[0] = intList;
	String s = stringLists[0].get(0);  // ClassCastException 발생! 
}
```

### 왜 제네릭 varargs 매개변수를 받는 메서드를 가능하게 만들었나?
- `List<String>[] stringLists = new List<String>[1];` 불가능
- 모순이 있지만 실무에서 유용함
- Arrays.asList(T.... a), Collections.addAll(Collection<? super T> c, T... elements)...

### 제네릭 varargs 매개변수를 안전하게 사용하는 방법 
- 가변인수를 담은 배열에 아무것도 저장하지 않는다.
- 배열의 참조를 외부에 노출하지 않는다.
- 순수하게 값을 전달하는 용도로만 쓴다.

**위의 조건으로 타입 안정성이 보장된다면 @SafeVarargs를 달아서 컴파일러 경고를 없애자!**

> java8에서는 오직 정적 메소드와 final 인스턴스 메서드에만 @SafeVarargs 붙일 수 있음 (재정의 메소드 안정성 믿을 수 없으므로..)
> java9에는 private 인스턴스 메서드에도 허용

### 타입 안정성을 깨는 예제
```java
static <T> T[] toArray(T... args) {
       // 런타임에 T가 소거되고 args 는 Object[] args 배열이 생성되고
       // 여기서 Object[] 참조가 반환됨
	return args;  
}

static <T> T[] pickTwo(T a, T b, T c) {
	switch (ThreadLocalRandom.current().nextInt(3)) {
		case 0: return toArray(a, b);
		case 1: return toArray(a, c);
		case 2: return toArray(b, c);
	}
	throw new AssertionError();
}

public static void main(String[] args) {
        // ClassCastException 발생! 
	String[] attributes = pickTwo("Good", "Fast", "Cheap"); // pickTwo() 반환 타입은 Object[]
}
```

### 타입 안정성을 지키는 예제
```java 
static <T> List<T> pickTwo(T a, T b, T c) {
    switch (ThreadLocalRandom.current().nextInt(3)) {
        // 타입 안정이 보장된 List.of()를 사용해서 Object[] 가 아닌 List<String>으로 반환
        case 0: return List.of(a, b);
        case 1: return List.of(a, c);
        case 2: return List.of(b, c);
    }
    throw new AssertionError();
}

public static void main(String[] args) {
    List<String> attributes = pickTwo("Good", "Fast", "Cheap");
}
```

### 결론 
- 제네릭 가변인수를 사용할 경우 아래 3가지 원칙을 꼭 지키자! 
```
- 가변인수를 담은 배열에 아무것도 저장하지 않는다.
- 배열의 참조를 외부에 노출하지 않는다.
- 순수하게 값을 전달하는 용도로만 쓴다.
```
- 위 원칙을 지켰다면 메소드에 @SafeVarargs 애너테이션을 달자!
