### ISSUE TITLE
아이템 42. 익명 클래스보다는 람다를 사용하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#42]

**Comment by bluewbear** [comment]
## item 42 : 익명 클래스보다는 람다를 사용하라

- 옛날에는 함수타입을 표현할때 추상 메서드를 하나만 담은 인터페이스(혹은 추상 클래스)를 사용
  - function object 함수 객체, 특정 함수나 동작을 나타냄
  - 익명클래스 
    - 일시적으로 한번만 사용하는 경우 : UI 이벤트 처라, 스레드 객체 등 ..
    - 재사용성이 없고, 확장성을 활용하는 것이 유지보수에서 더 안 좋은 상황일때 : 비즈니스 로직이 재각각이어 공통분모가 없는 경우 매번 클래스를 생성해야하는 비용이 더 많을때 
  - ```java
     Collections.sort(words, new Comparator<String>() {
         public int compare(String s1, String s2) {
             return Integer.compare(s1.length(), s2.length());
         }
     }
    ```
  - 익명 클래스 방식은 코드가 너무 길기 때문에 자바는 함수형 프로그래밍에 적합하지 않았다.
- java 8에 와서 람다식 lambda expression 도입 
  - 함수나 익명클래스와 개념은 비슷하지만 코드는 훨씬 간결 
  - ```java
     Collections.sort(words, 
         (s1, s2) -> Integer.compare(s1.length(), s2.length())
     );
    ```
  - s1, s2? 어떤 타입? return은? 어떤 타입?
    - 컴파일러가 문맥을 살펴 타입을 추론 
    - 컴파일러가 타입을 추론하지 못한다면 해당 타입을 명시하면 됨 
    - 컴파일러가 타입을 추론하는데 필요한 정보는 대부분 제네릭에서 얻는다.
      - item 26 제네릭의 로 타입을 쓰지 말라
      - item 29 제네릭 사용
      - item 30 제네릭 메소드 사용
  - 람다식에 비교자 생성 메서드를 사용하면 더 코드를 간결하게 변경할 수 있다.
  - ```java
     Collections.sort(words, comparingInt(String::length));
     words.sort(comparingInt(String::length)); // java 8 List 인터페이스에 추가된 sort 메소드 활용 
    ```
    - 한줄 컷~
- item34 Operation 열거 타입을 변경해보자
  - ```java
    public enum Operation {
        PLUS("+") {
            public double apply(double x, double y) { return x+y; }
        },
        MINUS("-") {
            public double apply(double x, double y) { return x-y; }
        },
        TIMES("*") {
            public double apply(double x, double y) { return x*y; }
        },
        DIVIDE("/") {
            public double apply(double x, double y) { return x/y; }
        };

        private final String symbol;

        Operation(String symbol) { this.symbol = symbol; }
     
        @Overide public String toString() { return symbol; }
        public abstract double apply(double x, double y);
    }
    ```
  - ```java
    public enum Operation {
        PLUS("+", (x, y) -> x + y),
        MINUS("-", (x, y) -> x - y),
        TIMES("*", (x, y) -> x * y),
        DIVIDE("/", (x, y) -> x / y);

        private final String symbol;
        private final DoubleBinaryOperation op;  // Double 타입 인수 2개를 받아 Double 타입 결과를 전달 

        Operation(String symbol, DoubleBinaryOperation op) { 
            this.symbol = symbol; 
            this.op = op;
        }
     
        @Overide public String toString() { return symbol; }

        public double apply(double x, double y) {
            return op.applyAsDouble(x, y);
        }
    }
    ```
- 람다의 단점?
  - 이름도 없고, 문서화도 못 한다.
  - 코드 자체로 명확하게 설명되지 않거나, 코드 줄수가 많아지면 람다 사용 자제
  - 3줄로 끝내는 것이 좋다.
- 람다의 시대이지만 대체할 수 없는 곳은 여전히 존재
  - 추상 클래스의 인스턴스를 만들때 익명 클래스 사용 
  - 추상 메서드가 여러 개인 인터페이스의 인스턴스를 만들때 익명 클래스 사용 
  - 람다는 자신을 참조할 수 없다. this는 바깥 인스턴스 자신
- 람다도, 익명 클래스도 이것만은 안된다.
  - 직렬화 형태가 머신 구현별로 다를 수 있으니 사용하지 말것.
