### ISSUE TITLE
아이템 44. 표준 함수형 인터페이스를 사용하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#44]

**Comment by windowforsun** [comment]
### 표준 함수형 인터페이스
- `java.util.function` 패키지에는 이미 다양한 용도의 `표준 함수형 인터페이스`가 존재한다. 
- 필요한 용도에 맞는 게 있다면, 직접 구현하지 말고 `표준 함수형 인터페이스`를 활용하자. 
  - API가 다루는 개념의 수가 줄어들어 관리가 용이함
  - 해당 함수형 인터페이스에 맞는 디폴트 메소드를 제공해서 다른 코드와 상호운용성 증가

```java
@FunctionalInterface
public interface Predicate<T> {
    boolean test(T t);

    default Predicate<T> and(Predicate<? super T> other) {
        // ..
    }

    default Predicate<T> negate() {
        // ..
    }

    default Predicate<T> or(Predicate<? super T> other) {
        // ..
    }

    // ..
}
```

### 기본 함수형 인터페이스
- [java.util.function](https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html) 에는 총 43종의 `표준 함수형 인터페이스` 가 존재
- 종류는 많지만 `기본 함수형 인터페이스` 와 그 변형에 대한 규칙만 알면 간단하다!
- 이중 6종 `기본 함수형 인터페이스` 를 정리하면 아래와 같음


인터페이스 | 설명 | 함수 시그니처 | 예
-- | -- | -- | --
UnaryOperator<T> | 반환값과 인수의 타입이 같은 함수(인수가 1개) | T apply(T t) | String::toLowerCase
BinaryOperator<T> | 반환값과 인수의 타입이 같은 함수(인수가 2개) | T apply(T t1, T t2) | BigInteger::add
Predicate<T> | 인수 하나를 받아서 boolean을 반환하는 함수 | boolean test(T t) | Collection::isEmpty
Function<T,R> | 인수와 반환 타입이 다른 함수 | R apply(T t) | Arrays::asList
Supplier<T> | 인수를 받지 않고 값을 반환(제공)하는 함수 | T get() | Instant::now
Consumer<T> | 인수를 하나 받고 반환값은  없는(특히 인수를 소비하는) 함수 | void accept(T t) | System.out::println

### 기본 함수형 인터페이스의 변형
- 기본 인터페이스는 기본 타입인 `int`, `long`, `double` 용으로 각 3종의 변형이 존재함(18종)

```java
// int 를 받는 Predicate
@FunctionalInterface
public interface IntPredicate { boolean test(int v); }

// long 을 받아 long 을 반환하는 BinaryOperator
@FunctionalInterface
public interface LongBinaryOperator { long applyAsLong(long v1, long v2); }
```

- `Function` 은 기본 타입을 반환하는 9종 변형이 존재함(`SrcToResult` 형식)

```java
// long 을 받아 int 를 반환
@FunctionalInterface
public interface LongToIntFunction { int applyAsInt(long v); }
```

- 추가로 `Function` 은 객체 참조를 받아 기본 타입을 반환하는 6종 변형이 존재

```java
// 객체 참조를 받아 long 을 반환
@FunctionalInterface
public interface ToLongFunction<T> { long applyAsLong(T v) }
```

- 기본 함수형 인터페이스 중 3개는 인수를 2개 받는 변형 3종 존재

```java
@FunctionalInterface
public interface BiPredicate<T, U> { boolean test(T t, U u) }

@FunctionalInterface
public interface BiFunction<T, U, R> { R apply(T t, U u); }

@FunctionalInterface
public interface BiConsumer<T, U> { void accept(T t, U u); }
```

- `BiFunction` 은 아래와 같이 기본 타입을 반환하는 3종의 변형 존재

```java
@FunctionalInterface
public interface ToIntBiFunction<T, U> { int applyAsInt(T t, U u); }
```

- `BiConsumer` 는 객체 참조와 기본 타입을 인수로 받는 3종 변형 존재

```java
@FunctionalInterface
public interface ObjDoubleConsumer<T> { void accept(T t, double v); }
```

- `Supplier` 는 `boolean` 값을 반환하는 변형 존재

```java
@FunctionalInterface
public interface BooleanSupplier { boolean getAsBoolean(); }
```

### 주의사항
- 앞서 설명한 것처럼 기본 타입에 대한 표준 함수형 인터페이스는 모두 존재한다. 
- 그러므로 박싱된 기본 타입을 넣어 사용하는 것은 지양하자 (#61 )
  - 복잡한 연산이 존재할 경우 성능에 영향을 미칠 수 있다. 
- 대부분의 경우 `표준 함수형 인터페이스` 를 사용할 수 있기 때문에 직접 구현하지 말자. 

### 직접 힘수형 인터페이스를 구현해야 하는 경우
- `Comparator` 과 `ToIntBiFunction` 은 구조적으로 동일하지만 모두 구현된 상태이다. 

```java
@FunctionalInterface
public interface Comparator<T> { int compare(T t1, T t2); }

@FunctionalInterface
public interface ToIntBiFunction<T, U> { int applyAsInt(T t, U u); }
```

- `Comparator`(1.2) 구현 당시 `ToIntBiFunction`(1.8) 이 존재하더라도 `Comparator` 은 별도 구현이 맞다. 
- `Comparator` 의 사례를 빌려 아래 중 하나를 만족하면 직접 함수형 인터페이스 구현을 고민해 볼 필요가 있다. 
  - 인터페이스 이름 자체가 용도를 명확히 설명한다. 
  - 반드시 따라야 하는 규약이 있다. 
  - 유용한 디폴트 메소드를 제공한다.  

> (추가) 함수형 인터페이스에서 예외를 던져야 하는 경우


### @FunctionalInterface
- 함수형 인터페이스를 구현할 떄 필수로 사용해야 한다. 
- `@Override` 처럼 개발자 의도를 명시하는 용도이다. 
- 인터페이스가 람다용으로 설계 된 것을 알려 준다. 
- 인터페이스의 추상 메서드는 오직 1개임을 컴파일 타임에 보장할 수 있다.
- 위의 특징으로 추후 유지보수 과정에서 메소드 추가가 되는일을 방지 할 수 있다. 


### 함수형 인터페이스 사용시 주의사항
- 같은 위치의 인수로 받는 메서드를 다중 정의해서는 안 된다. 
- 이는 사용자로 하여금 모호함만 안겨주는 방식이다. 

```java
public interface ExecutorService extends Executor {
    <T> Future<T> submit(Callable<T> task);
    Future<?> submit(Runnable task);
}

```

- `submit` 메서드를 사용할떄 올바른 메서드를 알려주기 위해 형변환이 필요한 경우가 발생할 수 있다. (#52 )
