### ISSUE TITLE
아이템 49. 매개변수가 유효한지 검사하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#49]

**Comment by luckyDaveKim** [comment]
## 매개변수 유효성 검사
- 메서드 or 생성자의 매개변수 검사는 빨리 하자. (몸체가 시작되기 전)
  - 그렇지 않으면...
  - 오류를 감지하기 어렵다
  - 감지 하더라도 발생 지점을 찾기 어렵다
  - 메서드가 수행되는 중간에 모호한 예외를 던지며 실패할 수 있다.
  - 메서드가 잘못된 결과를 반환할 수 있다
  - 메서드는 잘 수행 되었지만, 이상한 상태의 객체를 만들어 미래에 알 수 없는 시점에 이 메서드와 관계없는 오류를 낼수있다


## 접근 제어자에 따른 매개변수 유효성 검사
- public, protected 메서드
  - 예외를 문서화 하자 : `@throws`
  - 유효성 검사를 하자 : `Objects.requireNonNull()`
- private 메서드
  - 패키지 제작자인 여러분이 유효한 값만 넘겨지리라는 것을 보증할 수 있고, 그렇게 해야만 한다.
  - `assert`를 사용해 검사를 하자

### public, protected 메서드는 예외를 문서화 하자
- `@throws` 사용으로 API 사용자가 제약을 지킬 가능성을 크게 높일 수 있다 (#74)

```java
/**
... 중략

 * <p>All methods and constructors in this class throw
 * {@code NullPointerException} when passed
 * a null object reference for any input parameter.

... 중략
 */
public class BigInteger extends Number implements Comparable<BigInteger> {

    /**
     * Returns a BigInteger whose value is {@code (this mod m}).  This method
     * differs from {@code remainder} in that it always returns a
     * <i>non-negative</i> BigInteger.
     *
     * @param  m the modulus.
     * @return {@code this mod m}
     * @throws ArithmeticException {@code m} <= 0
     * @see    #remainder
     */
    public BigInteger mod(BigInteger m) {
        if (m.signum <= 0)
            throw new ArithmeticException("BigInteger: modulus not positive");
```

`@throws` 사용 예제이다. 이 메서드는 `m`이 `null`일 경우 NPE가 발생하며 이에 대한 설명은 클래스 수준에 명시했다.
> Tip! : 클래스 수준의 주석은 그 클래스의 모든 public 메서드에 적용되므로 각 메서드에 일일이 기술하는 것 보다 깔끔한 방법이다.


### public, protected 메서드에서 null 검사를 수동으로 하지 않고도 매개변수 유효성 검사하는 방법

- 코드
```java
System.out.println(Objects.requireNonNull(null).toString()); // 예외 발생
System.out.println(Objects.requireNonNull("Good"));

System.out.println(Objects.requireNonNull(null, "오류 메시지").toString()); // 예외 발생
System.out.println(Objects.requireNonNull("Good", "오류 메시지"));

System.out.println(Objects.requireNonNullElse(null, "default object"));
System.out.println(Objects.requireNonNullElse("Good", "default object"));
```

- 결과
```text
java.lang.NullPointerException
Good

java.lang.NullPointerException("오류 메시지")
Good

default object
Good
```

> Tip! : 값을 사용하는 동시에 null 검사를 수행할 수 있다.


### private 메서드는 `assert`를 사용해 검사를 하자
- assert는 VM 옵션을 주지 않으면 런타임에 아무런 효과 및 성능 저하가 없다.
(-ea | --enableassertions 옵션)
- 실패하면 AssertionError 던진다.

- 코드
```java
public class Main {
	public static void main(String[] args) {
		Article article1 = new Article(1L);
		System.out.println(article1);

		Article article2 = new Article(2L);
		System.out.println(article2);

		Article article3 = new Article(-1L);
		System.out.println(article3);
	}

	public static class Article {
		private final Long id;

		public Article(Long id) {
			validate(id);

			this.id = id;
		}

		private void validate(Long id) {
			assert id != null;
			assert id >= 0 : "음수 오류다";
		}

		@Override
		public String toString() {
			return "Article{" +
				"id=" + id +
				'}';
		}
	}
}
```

- 결과
```text
Article{id=1}
Article{id=2}
AssertionError("음수 오류다")
```

> Tip! : assert 검증문 뒤에  `: {메시지}` 를 통해 AssertionError 메시지를 지정할 수 있다.


## 메서드 몸체 실행 전에 매개변수 유효성 검사 규칙의 예외
- 유효성 검사 비용이 지나치게 높은 경우
- 계산 과정에서 암묵적으로 검사가 수행되는 경우
  - `Collections.sort(List)`의 경우 리스트 안의 객체들은 상호 비교될 수 있어야 하지만, 정렬 과정에 비교를 진행하므로 별도의 유효성 검사를 할 필요가 없다.
