### ISSUE TITLE
아이템 53. 가변인수는 신중히 사용하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#53]

**Comment by qlqhqo2341** [comment]
# 가변인수는 신중히 사용하라

- 가변인수(varargs)메서드는 명시된 타입의 인수를 0개 이상 받을 수 있는 메서드
- 인수 갯수가 일정하지 않은 메서드를 만들 때 사용함.
- 호출할 때마다 배열을 생성하게됨.
- printf와 리플렉션(#65)API도 가변인수를 사용하고 있음.

#### 예시
```java
static int sum(int... args) {
	int sum = 0;
	for (int arg: args) {
		sum += arg;
	}
	return sum;
}
```

#### 인수가 1개 이상이어야 할 때
```java
// BAD 
// 컴파일 타임에 오류를 잡지 못함.
// 코드가 지저분함.
static int min(int.. args) {
	if (args.length == 0) {
		throw new IllegalArgumentException("인수가 1개 이상 필요합니다.")
	}
	int min = args[0];
	for (int i=1;i<args.length; i++) {
		if (args[i] < min) {
			min = args[i];
		}
	}
	return min;
}

// GOOD
static int min(int firstArg, int.. remainingArgs) {
	int min = firstArg;
	for (int arg : remainingArgs) {
		if (arg < min) {
			min = arg;
		}
	}
	return min;
}
```


#### 배열을 매번 생성하고 싶지 않다면..?
- 이부분을 오버로딩을 통해서 개선시켜 보자!
	- 만약 95%가 인자 3개 이하인 메서드만 사용한다면..
	```java
	public void foo() { }
	public void foo(int a1) { }
	public void foo(int a1, int a2) { }
	public void foo(int a1, int a2, int a3) { }
	public void foo(int a1, int a2, int a3, int... rest) { }
	```
	- 나머지 5%의 실행에 대해서만 배열을 생성하게됨.
- EnumSet의 정적 팩터리도 이방법으로 열거타입 집합 생성비용을 최소화 하고있음.
	- 비트 필드를 대체할 수 있는 성능을 유지해야하므로 적절한 예
	- [jdk 관련 코드 링크](https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/share/classes/java/util/EnumSet.java#L200-L343)
