### ISSUE TITLE
아이템 56. 공개된 API 요소에는 항상 문서화 주석을 작성하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#56]

**Comment by KimYunsang-v** [comment]
**API를 쓸모 있게 잘 작성하려면 잘 작성된 문서도 곁들여하 한다.**

### 자바독(javadoc)
소스코드 파일에서 문서화 주석을 API문서로 변환해줌
API를 올바로 문서화하려면 공개된 모든 클래스, 인터페이스, 메서드, 필드 선언에 문서화 주석을 달아햐 한다.

### 문서화 주석 특징
- 메서드용 문서화 주석에는 해당 메서드와 클라이언트 사이의 규약을 명료하게 기술해야 한다.
  - 어떻게 동작하는지가 아니라 무엇을 하는지를 기술해야 한다. (how가 아닌 what을 기술)
  - 메서드를 호출하기 위한 전제조건(precondition)을 모두 나열해야 한다.
  - 메서드가 성공적으로 수행된 후에 만족해야  하는 사후조건(postcondition)도 모두 나열해야 한다.
  - 백그라운드 스레드 사용과 같은 시스템 상태의 변화를 가져오는 작업도 모두 밝혀야한다.
- 자바독은 문서화 주석을 HTML로 변환하므로 HTML 태그가 문서에 반영된다.
- 인스턴스 메서드의 주석의 `this`는 호출된 메서드의 객체를 가리킨다.
- 각 문서화 주석의 첫 번째 문장은 해당 요소의 요약 설명으로 간주됨 (클래스 or 인터페이스 내에서 중복되면 안됨)
  - 요약 설명 라인의 판단 기준은 { <마침표> <공백> <다음 문장 시작> } 이지만 자바10부터 요약 설명 전용 태그가 추가 됨 (`{@summary}`)
  - 메서드와 생성자의 요약 설명은 동작을 설명하는 동사구여야 함 
  - 클래스, 인터페이스, 필드의 요약 설명은 대상을 설명하는 명사절이어야 함
- 자바 9부터는 자바독이 생성한 HTML 문서에 검색(색인) 기능이 추가됨
  - 클래스, 메서드, 필드 같은 API 요소의 색인은 자동 생성됨
  - `@{index}` 태그로 직접 추가도 가능
- 제네릭 타입이나 제네릭 메서드를 문서화할 때는 모든 타입 매개변수에 주석을 달아야 함
- 열거 타입을 문서화할 때는 상수들에도 주석을 달아야 함
- 애너테이션 타입을 문서화할 때는 멤버들에도 모두 주석을 달아야 함 
  - 요약 설명은 이 애너테이션을 단다는 것이 어떤 의미인지 설명하는 동사구로 작성
  - 필드 설명은 명사구로 함
- 패키지를 설명하는 문서화 주석은 `package-info.java` 파일에 작성
- 모듈 시스템의 설명은 `module-info.java` 파일에 작성
- 클래스 혹은 정적 메서드의 스레드 안전 수준을 반드시 API 설명에 포함해야함
  - 스레드 안전 여부에 관계없이 반드시 작성
- 자바 `-Xdoclint` 옵션을 사용하면 자바독 문서 검사를 해줌 (checkstyle 플러그인 사용해도 좋음)
- 자바 `-html5` 옵션을 사용하면 HTML5 버전으로 만들어 줌

### 문서화 주석 태그 설명

- `@param`
  - 해당 매개변수가 뜻하는 값을 마침표 없이 명사구로 작성
- `@return`
  - 메서드 반환값을 마침표 없이 명사구로 작성
- `@throws`
  - 발생할 가능성이 있는 모든 예외를 마침표 없이 작성
- `@code`
  - 코드용 폰트로 렌더링됨 (HTML 요소 무시)
  - 여러줄로 작성하려면 `<pre> {@code ... 코드 ... } </pre>` 형태로 사용
- `@implSpec` 
  - 자기사용 패턴?에 대해서 문서화할 때 사용한다.
  - 해당 메서드와 하위 클래스 사이의 계약을 설명한다.
  - 하위 클래스들이 이 메서드를 상속하거나 `super` 키워드로 호출할 때 이 메서드가 어떻게 동작하는지 설명해야함
- `{@literal}`
  - 주석 내에서 HTML 마크업이나 자바독 태그 무시
  - 코드 폰트로 렌더링되지는 않음
- `{@summary}`
  - 요약 설명 전용 태그 (자바 10부터)
- `{@index}`
  - 감싸진 용어를 색인화 한다.
- `{@inheritDoc}`
  - 상위 타입의 문서화 주석 일부를 상속할 수 있음 

### 결론 
**자바독을 사용하여 API 문서화를 잘하자!!**

**Comment by KimYunsang-v** [comment]
### javadoc 만드는 방법
- https://github.com/NMP-Study/EffectiveJava2018/issues/56
