### ISSUE TITLE
아이템 58. 전통적인 for 문보다는 for-each 문을 사용하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#58]

**Comment by bluewbear** [comment]
## item 58 : 전통적인 for문 보다는 for-each문을 사용하라

- 컬렉션 순회 - 전통적인 방법 1
  - ```java
     for (Iterator<Element> i = c.iterator(); i.hasNext(); ) {
       Element e = i.next();
       .....
     }
     ```
- 컬렉션 순회 - 전통적인 방법 2
  - ```java
     for (int i = 0 ; i < a.length ; i++) {
       Element e = a.get(i);
       .....
     }
     ```
- `while`문 보다는 낫다! (item57)
  - 그렇지만 가장 좋은 방법은 아니다.
  - 우리에게 진짜 필요한 것은 "원소"들뿐 
- 잘못된 변수를 사용했을 때 컴파일러가 잡기가 어렵다.
- 컬렉션이냐 배열이냐에 따라 코드 작성 방식도 달라진다.
- `for-each`를 사용하면 모두 해결 가능!
  - **"향상된 for문(enhanced for statement)"**
  - 반복자, 인덱스를 사용하지 않으니 깔끔한 코드, 오류도 미연 방지
  - 컬렉션, 배열 모두 처리 가능 
  - ```java
     for (Element e : elements) {
       .....
     }
     ```
  - "elements안의 각 원소 e에 대해"
- 반복문 중첩해서 사용할 때의 실수를 찾아보자.
  - <img width="800" alt="스크린샷 2023-02-01 오전 12 40 31" src="https://user-images.githubusercontent.com/18572514/215806481-75c65a7d-72b3-4a85-99ff-4b052e37d67e.png">
  - 처음에는 뭔가 문제인지 바로 인지가 안된다... 
  - 문제는 `i.next()`
    - 두번째 중첩문이 for문을 순회하는 동안 i는 한개로 고정이어야 하는데 Rank의 원소가 다 돌때까지 next로 호출된다는 점
    - 결국 `NoSuchElementException`을 던진다.
- 같은 버그, 다른 증상!
  - <img width="500" alt="스크린샷 2023-02-01 오전 12 46 46" src="https://user-images.githubusercontent.com/18572514/215808196-c0f45489-7eb4-4531-890d-3c3e4baf319b.png">
  - 오류는 나지 않지만 우리가 원하는 결과가 나오진 않았다.
- 바깥 반복문에 바깥 원소를 저장하는 변수를 하나 추가해서 한번 개선
    - <img width="800" alt="스크린샷 2023-02-01 오전 12 50 14" src="https://user-images.githubusercontent.com/18572514/215809128-03ea8acd-653e-4f91-8a25-a3ef76f320fd.png">
    - ```
       [suit : CLUB, rank : ACE, suit : CLUB, rank : DEUCE, suit : CLUB, rank : THREE, suit : CLUB, rank : FOUR, suit : CLUB, rank : FIVE, suit : CLUB, rank : SIX, suit : CLUB, rank : SEVEN, suit : CLUB, rank : EIGHT, suit : CLUB, rank : NINE, suit : CLUB, rank : TEN, suit : CLUB, rank : JACK, suit : CLUB, rank : QUEEN, suit : CLUB, rank : KING, suit : DIAMOND, rank : ACE, suit : DIAMOND, rank : DEUCE, suit : DIAMOND, rank : THREE, suit : DIAMOND, rank : FOUR, suit : DIAMOND, rank : FIVE, suit : DIAMOND, rank : SIX, suit : DIAMOND, rank : SEVEN, suit : DIAMOND, rank : EIGHT, suit : DIAMOND, rank : NINE, suit : DIAMOND, rank : TEN, suit : DIAMOND, rank : JACK, suit : DIAMOND, rank : QUEEN, suit : DIAMOND, rank : KING, suit : HEART, rank : ACE, suit : HEART, rank : DEUCE, suit : HEART, rank : THREE, suit : HEART, rank : FOUR, suit : HEART, rank : FIVE, suit : HEART, rank : SIX, suit : HEART, rank : SEVEN, suit : HEART, rank : EIGHT, suit : HEART, rank : NINE, suit : HEART, rank : TEN, suit : HEART, rank : JACK, suit : HEART, rank : QUEEN, suit : HEART, rank : KING, suit : SPADE, rank : ACE, suit : SPADE, rank : DEUCE, suit : SPADE, rank : THREE, suit : SPADE, rank : FOUR, suit : SPADE, rank : FIVE, suit : SPADE, rank : SIX, suit : SPADE, rank : SEVEN, suit : SPADE, rank : EIGHT, suit : SPADE, rank : NINE, suit : SPADE, rank : TEN, suit : SPADE, rank : JACK, suit : SPADE, rank : QUEEN, suit : SPADE, rank : KING]
       ```
- `for-each`문을 중첩으로 간결하게
  - <img width="780" alt="스크린샷 2023-02-01 오전 12 52 49" src="https://user-images.githubusercontent.com/18572514/215810046-a8c55df3-8f15-4c67-99ca-308a9521c251.png">
  - 결과는 위의 것과 동일
- `for-each`를 사용하지 못하는 상황도 있다.
  - 1. 파괴적인 필터링 (destructive filtering) 
    - 컬렉션을 순회하면서 원소를 제거하는 경우, remove method를 호출 
    - 자바 8부터는 Collection의 `removeIf` method를 사용해 컬렉션을 명시적으로 순회하는 일을 회피 가능 
      - [removeIf 사용](https://kdhyo98.tistory.com/38)
  - 2. 변형 (transforming)
    - 리스트나 배열을 순회하면서 그 원소의 값, 혹은 전체를 교체하는 경우 
  - 3. 병렬 (parallel iteration) 
    - 여러 컬렉션을 병렬로 순회 
    - "버그를 찾아보자 코드"가 해당
  - 1 ~ 3번 상황에 해당된다면 일반적인 for문을 사용하되 item58에서 누누히 말하는 내용들을 경계해야함 
- `for-each`문은 컬렉션, 배열은 물론 `Iterable` interface를 구현한 객체라면 순회가 다 가능 

#### 마지막 정리

> 전통적인 for 문과 비교했을 때 for-each문은 명로, 유연, 버그를 예방
> 성능저하도 없으니, 가능한 모든 곳에서 for-each문을 사용하자!   

번외 ) [Iterator Pattern](https://velog.io/@cham/Design-Pattern-%EC%9D%B4%ED%84%B0%EB%A0%88%EC%9D%B4%ED%84%B0-%ED%8C%A8%ED%84%B4-iterator-pattern) 😁
