### ISSUE TITLE
아이템 60. 정확한 답이 필요하다면 float와 double은 피하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#60]

**Comment by windowforsun** [comment]
### float 와 double 타입은 과학과 공학 계산용으로 설계 됐다. 
- 이진 부동소수점 연산에 사용
- 넓은 범위의 수를 빠르고 정밀한 `근사치` 로 계산할수 있도록 설계
- 즉 정확한 계산 결과가 필요한 경우에는 사용해선 안됨
- 특히 금융 관련 계산과는 맞지 않음 (아래 예시)
  - `0.1`, `10^(-1)`, `10^(-2)` 를 표현할 수 없기 때문

```java
double result1 = 1.03 - 0.42;

assertThat(result1, not(0.61));
assertThat(result1, is(0.6100000000000001));

double result2 = 1.00 -9 * 0.10;

assertThat(result2, not(0.10));
assertThat(result2, is(0.09999999999999998));
```

- 결과값 출력전 반올림이 해법이 될수 있을 것같지만 그렇지 않음
  - 1달러를 가지고 10센트, 20센트, 30센트 .. 사탕을 하나씩 산다면 몇개의 사탕을 살수 있고 잔돈이 얼마 남는지 계산하는 프로그램

```java
double funds = 1.00;
int itemsBought = 0;

for(double price = 0.10; funds >= price; price += 0.10) {
    funds -= price;
    itemsBought++;
}

// 구매한 개수
assertThat(itemsBought, is(3));
// 구매 후 남은 잔돈
assertThat(funds, is(0.3999999999999999));
```

- 40센트 사탕도 구매할 수 있지만 결과값에서만 반올림 하는 방법으로는 해결 방법이 될 수 없음


### 정확한 계산 결과가 필요하다면 BigDecimal, int, long 을 사용하자
- 위 부정확한 프로그램에서 `double` -> `BigDecimal` 로 변경한 코드는 아래와 같음

```java
BigDecimal TEN_CENTS = new BigDecimal(".10");
BigDecimal funds = new BigDecimal("1.00");
int itemsBought = 0;

for(BigDecimal price = TEN_CENTS; funds.compareTo(price) >= 0; price = price.add(TEN_CENTS)) {
    funds = funds.subtract(price);
    itemsBought++;
}

// 구매한 개수
assertThat(itemsBought, is(4));
// 구매 후 남은 잔돈
assertThat(funds, is(new BigDecimal("0.00")));
```  

- `BigDecimal` 로 변경해서 정확한 결과를 얻어 냈지만 아래와 같은 단점이 있음
  - 기본(primitive) 타입보다 사용이 훨씬 불편하고 느리다
- `int`, `long` 을 대신 사용할 수 있지만 수 크기 제한이 있고, 소수점을 직접 관리해야 하는 번거러움이 있음
- 위 예제 프로그램은 `int` 타입을 사용하면서 단위를 센트로 모두 맞추면 간단하게 해결 될 수 있음

```java
int itemsBought = 0;
int funds = 100;

for(int price = 10; funds >= price; price += 10) {
    funds -= price;
    itemsBought++;
}

// 구매한 개수
assertThat(itemsBought, is(4));
// 구매 후 남은 잔돈
assertThat(funds, is(0));
```

### 정리
- 정확한 결과 값이 필요한 계산에서는 `float` 과 `double` 사용을 피해야 한다. 
- 소수점 처리는 시스템에 맡기고, 성능 저하를 신경 쓰지 않아도 된다면 `BigDecimal` 사용하는게 좋다. 
- 성능이 중요하고 소수점 처리가 가능하면서 숫자가 크지 않다면 `int`, `long` 사용하는게 좋다. 
  - `int` : 9자리
  - `long` : 18자리
  - `BigDecimal` : 18자리를 넘는 경우에는 어쩔 수 없으 사용
