### ISSUE TITLE
아이템 61. 박싱된 기본 타입보다는 기본 타입을 사용하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#61]

**Comment by qlqhqo2341** [comment]
# 박싱된 기본타입 보다는 기본 타입을 사용하라.
### 개요
- 자바의 데이터 타입 분류
	- 기본 타입
	- 참조 타입
- 모든 기본 타입은 대응하는 참조타입이 있음.
- 오토박싱과 오토언박싱이 있어 두 타입을 구분하지 않고 사용할 수 있다.
	- 하지만 둘 사이의 차이점이 있으니 분명히 구분하고 써야한다.

### 박싱된 기본타입과 기본타입의 차이점
1. 기본타입은 값만 가지고 있으나, 박싱이 되면 식별성을 갖는다.
   => 값이 같지만 서로 다르다고 식별될 수 있다.
2. 박싱되면 유효하지 않은 null값을 가질 수 있다..
3. 기본타입이 더 효율적이다.

#### 1. 식별성을 간과한 구현
```java
Comparator<Integer> natrualOrder = 
	(i, j) -> (i < j) ? -1 : (i == j ? 0 : 1);

// error case
natrualOrder.compare(new Integer(42), new Integer(42))


// fix
Comparator<Integer> naturalOrder = (iBoxed, jBoxed) -> {
	int i = iBoxed, j = jBoxed; // 오토박싱
	return i < j ? -1 : (i == j ? 0 : 1)
}

```
> 책에 이후 별다른 언급은 없었지만.. comparator에 npe 위험이 여전히 존재한다.


#### 2. null 가능성을 간과한 구현
```java
public class Unbelievable {
	 static Integer i;
	 
	 public static void main(String[] args) {
		 if (i == 42)
			 System.out.println("믿을 수 없군!");
	 }
}
```
- 조건문의 문자열을 출력하게 되진 않으나.. 
	- **기본 타입과 박싱된 기본타입을 혼용한 연산에서는 오토언박싱이 일어남**
	- **NPE 발생!**
- `Integer`가 아닌 `int`로 선언하자.

#### 3. 오토박싱/언박싱의 비효율을 간과한 구현 (#6)
```java
public static void main(String[] args) {
	Long sum = 0L;
	for (long i = 0; i <= Integer.MAX_VALUE; i++) {
		sum += i;
	}
	System.out.println(sum);
}
```
- 지역 변수 sum을 박싱된 기본타입을 선언해서,
  박싱과 언박싱이 계속 일어나서 체감될 정도로 성능이 느려짐

### 박싱된 기본타입이 적절한 경우?
1. 컬렉션의 원소, 키 값을 쓸 때
	- 일반화 => 매개변수화 타입, 매개변수화 메소드의 타입 매개변수를 사용할 때
	- `ThreadLocal<int>` 는 사용할 수 없지만 `ThreadLocal<Integer>`는 사용 가능
2. 리플렉션을 통해 메소드를 호출하는 경우 (#65)

### 정리
- 기본타입, 박싱된 기본타입중 써야한다면 가능하면 기본타입!
- 박싱된 기본타입을 써야한다면, 주의를 기울여서 사용할 것.
