### ISSUE TITLE
아이템 64. 객체는 인터페이스를 사용해 참조하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#64]

**Comment by KimYunsang-v** [comment]
> "**매개변수 타입으로 클래스가 아니라 인터페이스를 사용하라**" 를 "**객체는 클래스가 아닌 인터페이스로 참조하라**" 로 확장 가능
> 참고: #51 


**적합한 언터페이스만 있다면 매개변수뿐 아니라 반환값, 변수, 필드를 전부 인터페이스 타입으로 선언하라.**
객체의 실제 클래스를 사용해야 할 상황은 오직 생성자로 생성할 때뿐이다.
> 인터페이스 타입으로 사용하는 습관은 프로그램을 훨씬 유연하게 해준다.

```java
// 좋은 예
Set<Son> sonSet = new LinkedHashSet<>();
// 나쁜 예
LinkedHashSet <Son> sonSet = new LinkedHashSet<>();
```

- 장점 
  - 추후에 성능 개선이나 신기능을 제공하는 클래스가 나왔을 경우 교체에 유연 (단순 교체시에도)
    - LinkedHashSet => HashSet
    - HashMap => EnumMap or LinkedHashMap
- 주의 
  -  구현체가 인터페이스의 규약 이외에 특별한 기능을 제공한다면 새로운 클래스도 반드시 같은 기능을 제공해야함
  - ex) LinkedHashSet은 원소의 순서를 보장하지만 HashSet은 순서 보장을 하지 않음

**만약 적합한 인터페이스가 없다면 클래스의 계층구조 중 필요한 기능을 만족하는 가장 상위의 클래스를 타입으로 사용하자**

#### 적합한 인터페이스가 없는 부류
- 값 클래스인 경우
  - String, BigInteger
- 클래스 기반으로 작성된 프레임워크가 제공하는 객체
  - OutputStream 등 java.io 패키지 하위
- 인터페이스에는 없는 특별한 메서드를 제공하는 클래스들
  - PriorityQueue는 (인터페이스에는 없는)comparator 메소드 제공
  - 이런 추가 메서드의 사용은 꼭 사용해야하는 경우로 최소화하는게 좋다.
