### ISSUE TITLE
아이템 65. 리플렉션보다는 인터페이스를 사용하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#65]

**Comment by luckyDaveKim** [comment]
### 리플렉션 단점
- 컴파일타임 타입 검사가 주는 이점을 하나도 누릴 수 없다.
- 리플렉션을 이용하면 코드가 지저분하고 장황해진다.
- 성능이 떨어진다.

### 리플렉션은 아주 제한된 형태로만 사용해야 그 단점을 피하고 이점만 취할 수 있다.
컴파일 타임에 이용할 수 없는 클래스를 사용해야 하는 경우 인스턴스 생성에만 사용하고, 이후 가능하다면 인터페이스나 상위 클래스를 이용하자.

```java
try {
    Class.forName(args[0]);
} catch (ClassNotFoundException e) {
    fatalError("클래스를 찾을 수 없습니다.");
}

try {
    clazz.getDeclaredConstructor();
} catch (NoSuchMethodException e) {
    fatalError("매개변수 없는 생성자를 찾을 수 없습니다.");
}

try {
    Set<String> set = constructor.newInstance();
} catch (IllegalAccessException e) {
    fatalError("생성자에 접근할 수 없습니다.");
} catch (InstantiationException e) {
    fatalError("클래스를 인스턴스화할 수 없습니다");
} catch (InvocationTargetException e) {
    fatalError("생성자가 예외를 던졌습니다.");
} catch (ClassCastException e) {
    fatalError("Set을 구현하지 않은 클래스입니다.");
}
```

인스턴스 생성에만...
- 런타임에 총 6가지나 되는 예외를 처리해야 한다.
  (Java 7 부터 리플렉션 예외를 ReflectiveOperationException 상위 예외로 한번에 처리 가능하다)
- 인스턴스 생성에 25줄의 코드 작성이 필요하다.

### 리플랙션 사용은
최대한 사용을 자제하도록 하며, 꼭 필요시에는 객체 생성에만 사용하고, 생성한 객체를 이용할 때는 적절한 인터페이스나 컴파일타임에 알 수 있는 상위 클래스로 형변환해 사용하자
