### ISSUE TITLE
아이템 66. 네이티브 메서드는 신중히 사용하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#66]

**Comment by bluewbear** [comment]
## item 66 : 네이티브 메서드는 신중히 사용하라

- Java Native Method
  -  자바 프로그램이 Native method를 호출 
- 네이티브 메서드란?
  - C, C++ 같은 언어로 작성된 프로그램 
- 주요 쓰임새 | 하지만?
  -- | -- 
  레지스트리 같은 플랫폼 특화 기능 사용 | 자바 버젼업하면서 os 같은 하부 플랫폼 기능을 흡수 <br> 자바9는 process API를 추가하여 OS 프로세스에 접근 가능 [UsageEX](https://www.baeldung.com/java-9-process-api), [API](https://docs.oracle.com/javase/9/docs/api/java/lang/Process.html)
  네이티브 코드로 작성된 기존 라이브러리 활용 | 
  성능 개선을 목적으로 성능에 결정적인 영향을 <br>주는 영역만 따로 네이티브 언어로 작성 | 성능을 개선할 목적으로 네이티브 메서드 사용은 권장하니 않음
- 그래도 사용할만 네이티브 라이브러리는?
  - GNU 다중 정밀 연산 라이브러리 (GMP) : GNU Multiple-Precision Library [위키백과](https://ko.wikipedia.org/wiki/GMP_(%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC))
- 네이티브 메서드의 심각한 단점
  - 네이티브 언어가 안전하지 않으니 메모리 훼손 오류로부터 안전하지 않다 [Item 50](https://github.com/NMP-Study/EffectiveJava2022/issues/50)
  - 네이티브 언어는 플렛폼을 많이 타서 이식성이 낮다.
  - 디버깅도 쉽지 않다.
  - 가비지 컬렉터가 네이티브 메모리는 자동 회수하지 못하고, 추적도 어렵다. [Item 8](https://github.com/NMP-Study/EffectiveJava2022/issues/8)
  - 자바와 네이티브 메서드 사이의 "접착 코드(glue code)"를 작성해야하는데 귀찮다. 가독성도 안 좋다.
    - [JNI 사용법 및 예제](https://recordsoflife.tistory.com/720)

### 결론

- 네이티브 메서드를 사용하려거든 한번 더 생각해라~
