### ISSUE TITLE
아이템 68. 일반적으로 통용되는 명명 규칙을 따르라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#68]

**Comment by windowforsun** [comment]
# 자바 명명 규칙
- [jls-6.1](https://docs.oracle.com/javase/specs/jls/se9/html/jls-6.html#jls-6.1) 에서 자세한 명명 규칙을 확인 할 수 있다. 
- 명명 규칙은 크게 아래 2가지 범주로 구분 된다. 
  1. 철자
  2. 문법

## 철자 규칙
- 철자 규칙은 패키지, 클래스, 인터페이스, 메서드, 필드, 지역변수, 타입 매개변수를 다룬다. 
- 특별한 이유가 있지 않다면 반드시 따라야 한다. 
- 철자 규칙을 어긴다면 `API` 사용과 유지보수가 어렵다. (의미를 오해하거나 더 나아가 오류가 발생 할 수 있음)

### 패키지와 모듈 이름
- 점(.)으로 구분하여 계층적으로 짓는다. 
- 요소는 소문자 알파벳, 숫자(드물게)로 이뤄진다. 
- 조직 외부에서 사용될 수 있다면 도메인 이름 역순으로 기술한다.
  - `edu.cmu`
  - `com.google`
  - `com.naver.news`
- 각 요소는 해당 패키지를 표현할 수 있는 8자 이하 짧은 단어를 사용한다.
  - `utilities` 보다는 의미가 통하는 `util` 과 같은 약어
- 여러 단어로 구성된다면 `awt` 처럼 각 단어 첫 글자만 따서 써도 좋다. 
- 많은 기능을 제공하는 경우엔 계층을 나눠 더 많은 요소로 하위 패키지(`subpackage`)를 구성해도 좋다. 
  - `java.util` 하위에 `java.util.concurrent.atomic`, `java.util.concurrent.locks` 와 같이 


### 클래스와 인터페이스 이름(Enum, 애너테이션 포함)
- 하나 이상의 단어로 이뤄지고 각 단어는 대문자로 시작한다.
  - `List`, `FutureTask`
- 약자나(여러 단어의 첫 글자만 딴) `min`, `max` 와 같이 널리 통용되는 줄임말을 제외하고는 단어를 줄여 쓰지 않는다. 
- 약자의 경우 첫 글자만 대문자로 할지 모두 대문자로 할지 논란이 있지만, 첫 글자만 대문자로 쓰는 경우가 많다.
  - `HttpUrl`, `HTTPURL` 을 비교 했을 떄 무엇이 더 나은가.. ?

### 메서드와 필드 이름
- 첫 글자를 소문자로 쓴다는 점만 빼면 클래스 명명 규칙과 동일하다. (Camel case)
  - `remove`, `removeAll`
- 첫 단어가 약자라면 약자 전체를 소문자로 쓴다. 
  - `awt`
- `상수 필드` 는 예외적으로 모두 대문자와 단어 사이에 밑줄(_)로 구분한다. (값이 불변인 `static final` #17 )
  - `VALUES`, `SECTION_ID`
  - 이름에 밑줄을 사용하는 요소는 상수 필드가 유일하다. 

### 지역변수 이름
- 다른 멤버와 동일한 규칙이 적용된다. 
- 추가적으로 약어를 사용해도 좋다. 
  - `i`, `num`

### 타입 매개변수 이름
- 일반적으로 한 문자로 표현하고, 대부분 아래 6가지 중 하나다. 
  - `T` : 임의의 타입(Type)
  - `E` : 컬렉션 원소 타입(Element)
  - `K` : 맵의 키 타입(Key)
  - `V` : 맵의 값 타입(Value)
  - `X` : 예외 타입(eXception)
  - `R` : 매서드 반환 값 타입(Return)
  - `T, U, V`, `T1, T2, T3` : 임의 타입 시퀀스


## 문법 규칙

### 클래스
- 객체를 생성 할 수 있는 클래스(Enum 포함)은 단수 명사나 명사구를 사용한다.
  - `Thread`, `PriorityQueue`, `LinkedList`
- 객체를 생성 할 수 없는 클래스는 복수형 명사를 사용한다. (#4 )
  - `Collectors`, `Collections`


### 인터페이스
- 클래스와 똑같이 하거나, `able`, `ible` 로 끝나는 형용사를 사용한다. 
  - `Collection`, `Runnable`, `Accessible`

### 애너테이션
- 지배적인 규칙 없이 명사, 동사, 전치사, 형용사가 두루 사용된다. 
  - `BindingAnnotation`, `Inject`, `ImplementedBy`, `Singleton`

### 메서드
- 동작을 수행하는 메서드는 동사나(목적어 포함) 동사구를 사용한다. 
  - `append`, `drawImage`
- `boolean` 값을 반환하는 경우는 `is`, `has`(드물게) 로 시작하고 명사, 명사구, 형용사로 끝난다. 
  - `isDigit`, `isEmpty`, `isEnabled`
- 반환 타입이 `boolean` 이 아니거나 해당 인스턴스의 속성을 반환하는 경우 명사, 명사구, 혹은 형용사로 가능한 단어나 구로 끝나도록 한다. 
  - `size`, `hashCode`, `length`, `getTime`
- 클래스가 한 속성의 `getter`, `setter` 를 모두 제공 한다면 `getX`, `setX` 와 같이 사용한다. 
  - `getAttribute`, `setAttribute`
- 객체의 타입을 바꿔 다른 타입 또는 객체를 반환하는 인스턴스 메서드는 `toType` 형태를 사용한다. 
  - `toString`, `toArray`
- 객체의 내용을 다른 뷰로 보여주는 메서드는 `asType` 형태를 사용한다. (#6 )
  - `asList`
- 객체의 값을 기본 타입으로 반환하는 메서드는 `typeValue` 형태를 사용한다.
  - `intValue`
- 정적 팩터리 이름은 아래의 것들을 흔히 사용한다. (#1 )
  - `from`, `of`, `valueOf`, `instance`, `getInstance`, `newInstance`, `getType`, `newType`

### 필드
- `API` 설계에 직접 노출 될 일이 거의 없으므로 덜 명확, 덜 중요하다. (설계를 잘 했다면)
- `boolean` 타입 필드는 `boolean` 접근자 메서드에서 앞 단어를 뺀 형태를 사용한다. 
  - `initialized`, `composite`
- 그외 타입 필드는 명사나 명사구를 사용한다.
  -`height`, `digits`, `bodyStyle`
- 지역변수는 비슷하지만, 더 느슨하다.

## 정리
- 표준 명명 규칙 체계화해서 자연스럽게 베어나오도록 하자
- 철자 규칙은 직관적인 반면 문법 규칙은 더 복잡하고 느슨하다. 
- 자바 언어 명세 인용 `"오랫동안 따라온 규칙과 충돌한다면 그 규칙을 맹종해서는 안 된다"`
  - 상식이 이끄는 대로 ...
