### ISSUE TITLE
아이템 69. 예외는 진짜 예외 상황에만 사용하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#69]

**Comment by qlqhqo2341** [comment]
# 69. 예외는 진짜 예외 상황에만 사용하라

예외를 완전히 잘못 사용한 예시
```java
try {
    int i = 0;
    while (true)
        range[i++].climb();
} catch (ArrayIndexOutOfBoundsException e) {
}
```
- 무슨 일을 하는 지 전혀 직관적이지 않음.
- for-each를 쓰는 것이 더 낫겠다.
---
#### 잘못된 생각
- JVM은 배열에 접근할 때마다 배열의 경계를 넘는지 검사함, 그렇다면 우리가 추가로 검사할 필요가 없다!
- 아래 3가지 이유로 잘못된 추론
    - 예외는 예외상황에서만 쓰도록 설계되었으므로, 빠르지 않을 확률이 높음.
    - 코드를 try-catch에 넣으면 jvm이 최적화하지 못하는 부분이 생김.
    - 배열 순회를 하는 표준 관용구는 중복 검사를 하지 않도록 JVM이 알아서 최적화함.
- 또 다른 문제점
    - `ArrayIndexOutOfBoundsException`이 내부의 다른데서 던져지면, 해당 오류처리를 쓸 수 없는 문제도 있음.
---
#### 정상 상황에서 예외를 쓰지 않도록 설계된 API
- 상태의존적 메서드
    - `Iterator.next`
- 상태 검사 메서드
    - `Iterator.hasNext`
- 두 개를 모두 제공 해야함!
```java
// 만약 hasNext가 없다면 아래처럼 깔끔하게 순회하지 못할 것이다.
for (Iterator<Foo> i = collection.iterator(); i.hasNext(); ) {
    Foo foo = i.next();
}
```
- 상태 검사 메소드가 아닌 Optional 혹은 null같은 값을 반환하는 것이 나을 경우
    - 다중 스레드 상황 혹은 다른 요인으로 상태가 변할 수 있을 때
    - 성능이 중요한데 의존적 메소드와 검사 메소드에 중복 로직이 많을 때
- 이외 경우 대부분 가독성때문에, 상태 검사 메소드가 더 나음.
---
### 정리
- 예외는 예외상황에서만 쓰고 정상적인 흐름에서는 쓰지말자.
- API를 만들때도 클라이언트 입장에서 이를 고려해서 만들자.
