### ISSUE TITLE
아이템 7. 다 쓴 객체 참조를 해제하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#7]

**Comment by KimYunsang-v** [comment]
# 메모리 누수의 주범 
* JAVA는 C, C++처럼 직접 메모리를 관리하지 않는다. 
* c 언어의 경우 메모리 할당 및 해제를 직접 관리한다. (malloc / free)
* JAVA는 GC가 알아서 다 쓴 객체를 회수해간다. 

=> GC만 믿고 메모리 관리에 신경쓰지 않는다면 메모리 누수가 발생할 수 있다!

## [1] 다 쓴 참조를 여전히 갖고 있는 경우 
#### JAVA에서도  **자기 메모리를 직접 관리하는 클래스**라면 메모리 누수에 주의해야 한다!

<details> 
   <summary>stack 예제</summary>

```java
public class Stack {
    private Object[] elements;
    private int size = 0;
    private static final int DEFAULT_INITIAL_CAPACITY = 16;

    public Stack() {
        elements = new Object[DEFAULT_INITIAL_CAPACITY];
    }

    public void push(Object e) {
        ensureCapacity();
        elements[size++] = e;
    }

    public Object pop() {
        if (size == 0)
            throw new EmptyStackException();
        return elements[--size];
    }

    private void ensureCapacity() {
        if (elements.length == size)
            elements = Arrays.copyOf(elements, 2 * size + 1);
    }

    public static void main(String[] args) {
        Stack stack = new Stack();
        for (String arg : args)
            stack.push(arg);

        while (true)
            System.err.println(stack.pop());
    }
}
```

</details>

- 위 Stack 코드 참고
   - 스택의 활성영역을 코드단에서 관리
   - 활성영역을 코드단에서 관리하다보니 가비지 컬렉터는 활성영역의 존재를 모름
   - 가비지 컬렉터는 비활성 영역에서 참조하는 객체도 똑같이 유효한 객체로 보고 회수하지 않음
- 해결책은, 해당 참조를 다 썼을 때 null  처리
- 그럼 모든 객체를 다 쓰고나서 일일이 null 처리 해야 하는가?
  - 객체 참조를 null 처리하는 일은 예외적인 경우에만
  - 가장 좋은 방법은 그 참조를 담은 변수를 유효 범위(scope) 밖으로 밀어내는 것!

## [2] 캐시
#### 객체 참조를 캐시에 넣고, 해당 객체를 다 쓴 뒤로도 그냥 놔두는 경우
  - 예를 들면 금융 서비스에서 거래되는 종목 코드값을 캐싱처리하기 위해 HashMap에 담아 두었는데, 상장폐지가 된 종목들 (더 이상 사용하지 않는, 비활성 종목코드)의 처리는 어떻게 되는건가..?
  
#### 해결책
- WeakHashMap을 사용해 캐시를 관리
  - 다 쓴 엔트리는 그 즉시 자동으로 제거 (스펙 확인은 하위 링크를 참고)

## [3] 리스너 혹은 콜백
#### 클라이언트가 콜백 등록 후 명확히 해지하지 않는다면 콜백은 계속 쌓여감
#### 해결책 
  - 콜백을 약한 참조로 저장하여 가비지 컬렉터가 즉시 수거해가도록 함
     - 예) WeakHashMap에 키로 저장

#### WeakHashMap 란?
- 어떤 key 가 null 이 되면 해당 key/value pair를 제거
  - map 에 put 하는 시점에 key 들이 유효한지 체크! 
  - 체크는 ReferenceQueue 를 사용!
-  단, String이나 primitive boxing object는 JVM 별도 공간에 캐싱되므로 사용에 주의!
- 단2, value가 key를 참조하는 형태라면 key가 삭제되지 않음 
  - value를 WeakReferences 다시 래핑하는 방식을 사용해야함
  - ex) `m.put (key, new WeakReference (value))`


## 참고 
- reference 종류에 따른 GC 여부 참고 ((java.lang.ref 패키지 - Soft, Weak, Phantom Reference)
  - https://d2.naver.com/helloworld/329631

**Comment by KimYunsang-v** [comment]
### 이펙티드 자바 코드 repo 
https://github.com/jbloch/effective-java-3e-source-code
