### ISSUE TITLE
아이템 72. 표준 예외를 사용하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#72]

**Comment by KimYunsang-v** [comment]
예외도 다른 코드들과 마찬가지로 재사용하는 것이 좋음
자바 라이브러리는 대부분 API에서 쓰기에 충분한 예외를 제공한다.

### 예외 재사용 시 장점
- 내가 개발한 API가 다른사람이 익히고 사용하기 쉬워진다. 
- 낯선 예외를 사용하지 않아 읽기 쉬운 코드가 된다.
- 예외 클래스 수가 적을수록 메모리 사용량도 줄고 클래스를 적재하는 시간도 적게 걸린다.

### 예외 재사용 시 주의할 점
- Exeception, RuntimeException, Throwable, Error는 직접 재사용하지 말자.
  - 위 클래스는 추상 클래스라고 생각하는게 좋음
  - 여러 성격의 예외를 포괄하는 클래스이므로 안정적인 테스트가 어려워진다.
- API문서를 참고해 해당 예외가 어떤 상황에서 던져지는지 확인하자.
-  예외의 이름뿐 아니라 예외가 던져지는 맥락도 부합할 때 재사용하자.
- 예외는 직렬화할 수 있다.
  - 직렬화에는 많은 부담이 따르니 재사용하자.
  - 예외 클래스 수가 많을수록 메모리 사용량도 늘고 클래스를 로딩하는 시간도 더 걸린다.

### 많이 사용되는 주요 예외

[jdk17 doc](https://docs.oracle.com/en/java/javase/17/docs/api/index.html)

예외  | 주요 쓰임 
--|--
IllegalArgumentException | 허용하지 않는 값이 인수로 건네졌을 때 (null은 따로 NPE로 처리)
IllegalStateException | 객체가 메서드를 수행하기에 적절하지 않는 상태일 때
NullPointException | null을 허용하지 않는 메서드에 null을 건넸을 때 
IndexOutOfBoundsException | 인덱스가 범위를 넘어섰을 때
ConcurrentModificationException | 허용하지 않는 동시 수정이 발견됐을 때
UnsupportedOperationException | 호출한 메서드를 지원하지 않을 때


## 커스텀 예외 클래스를 구현할 때 참고하면 좋은 4가지 베스트 프랙티스

### 1. Always Provide a Benefit

표준 예외에서 제공하지 않는 정보나 기능을 제공해야한다.
어떠한 장점을 제공하지 않는 커스텀 예외를 사용하는 것보다는 표준 예외를 사용하는게 좋다.

### 2. Follow the Naming Convention

JDK가 제공하는 예외 클래스들을 보면 클래스의 이름들이 모두  `Exception`으로 끝난다.
자바 생태계 전체적으로 사용되는 규칙이라서 따르는게 좋다.

### 3. Provide Javadoc Comments for Your Exception Class

잘 만들어진 javaDoc과 문서화가 필요하다.
예외가 발생할 수도 있는 상황과 예외의 일반적인 의미를 기술해라.

### 4. Provide a Constructor That Sets the Cause

원인을 기술할 수 있는 생성자 메소드를 제공해라.
Exception과 RuntimeException은 예외의 원인을 기술하고 있는 Throwable을 받을 수 있는 생성자 메소드를 제공한다.
커스텀 예외에서도 발생한 Throwable을 파라미터를 통해 가져올 수 있는 생성자를 최소한 하나 구현하고 수퍼클래스에 Throwable을 전달해줘야 한다.

```java
public class MyBusinessException extends Exception {
    public MyBusinessException(String message, Throwable cause, ErrorCode code) {
            super(message, cause);
            this.code = code;
        }
        ...
}
```

> 참고: https://dzone.com/articles/implementing-custom-exceptions-in-java?fromrel=true
> 번역: https://m.blog.naver.com/sthwin/221144722072
