### ISSUE TITLE
아이템 73. 추상화 수준에 맞는 예외를 던지라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#73]

**Comment by luckyDaveKim** [comment]
## 상위 계층에서는 저수준 예외를 잡아 자신의 추상화 수준에 맞는 예외로 바꿔 던져야 한다.
이를 예외 번역(exception translation) 이라 함

### 생활 예시
- 로봇 청소기가 동작 중 바퀴에 무엇인가 끼었을 때, `1 뉴턴의 동력에도 3초이상 바퀴가 움직이지 않습니다` 대신, `바퀴에 이물질이 끼었습니다.` 라는 예외를 던지는게 알맞다.

1. 예외 번역
```java
try {
    ... // 저수준 추상화를 이용한다.
} catch (LowerLevelException e) {
   // 추상화 수준에 맞게 번역한다.
   throw new HigherLevelException(...);
}
```

2. 예외 연쇄
(저수준의 예외가 디버깅에 도움되는 경우)
```java
try {
    ... // 저수준 추상화를 이용한다.
} catch (LowerLevelException cause) {
   // 추상화 수준에 맞게 번역한다.
   throw new HigherLevelException(cause);
}
```

### 무턱대고 예외를 전파하는 것보다야 예외 번역이 우수한 방법이지만, 그렇다고 남용해도 곤란하다.
- 가능하다면 저수준 메서드가 반드시 성공하도록 처리
- 상위 계층 메서드의 매개변수 값을 아래 계층 메서드로 건네기 전 미리 검사
- 아래 계층에서의 예외를 피할 수 없다면, 상위 계층에서 예외를 조용히 처리 하고 로깅
