### ISSUE TITLE
아이템 74. 메서드가 던지는 모든 예외를 문서화하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#74]

**Comment by bluewbear** [comment]
## item 74 : 메서드가 던지는 모든 예외를 문서화하라

- [item56](https://github.com/NMP-Study/EffectiveJava2022/issues/56) : 메서드가 던지는 예외는 메서를 올바르게 사용하는데 아주 중요한 정보이니 예외 하나하나를 문서화를 하는데 충분한 시간을 쏟아야한다.
- 검사 예외는 항상 따로따로 선언! 각 예외가 발생하는 상황을 자바독의 `@throws` 태그를 사용하여 정확히 문서화하자.
  - 공통 상위 클래스 하나로 뭉뚱그려 선언하는 일은 삼가라. Exception. Throwable..
- 비검사 예외도 정성껏 문서화해두자.
- public 메서드라면 필요한 전제조건을 문서화 해야한다. (item56)
- 메서드가 던질 수 있는 예외를 각각 @throws 태그로 문서화하되, 비검사 예외는 메서드 선언의 throws 목록에 넣지 말자.
  - 검사냐 비검사냐에 따른 해야 할 일을 구분
- 한 클래스에 정의된 많은 메서드가 같은 이유로 같은 예외를 던진다면 그 예외를 클래스 설명에 추가하는 방법도 있다.
  - NullPointerException [Java 9 API](https://docs.oracle.com/javase/9/docs/api/java/lang/NullPointerException.html)
  - <img width="600" alt="스크린샷 2023-02-22 오전 1 32 18" src="https://user-images.githubusercontent.com/18572514/220404234-18dad03c-65d1-400c-bbf5-03379c15ceae.png">

> - 메서드가 던질 가능성이 있는 모든 예외를 문서화!
> - 검사든 비검사든 모두 해당!
> - @throws 활용
