### ISSUE TITLE
아이템 76. 가능한 한 실패 원자적으로 만들라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#76]

**Comment by windowforsun** [comment]
## 실패 원자적(failure-atomic)
호출된 메서드가 실패하더라도 해당 객체는 메서드 호출 전 상태를 유지해야 한다. 

### 불변 객체로 만든다. 
- 불변 객체(#17)은 실패 원자적이다. 
- 메서드가 실패하더라도 객체만 만들어지지 않을 뿐, 기존 객체가 불안정한 상태에는 빠지지 않는다. 
- 불변 객체상태는 생성 시점에 고정되고 변하지 않기 때문.


### 매개변수 유효성 검사를 한다. 

- 매개변수 유효성 검사(#49)를 통해 객체 상태 변경 전 예외를 걸러낸다. 

```java
// java.util.ArrayList

protected void removeRange(int fromIndex, int toIndex) {
    if (fromIndex > toIndex) {
        throw new IndexOutOfBoundsException(
                outOfBoundsMsg(fromIndex, toIndex));
    }
    modCount++;
    shiftTailOverGap(elementData, fromIndex, toIndex);
}
```


```java
// java.util.Stack

public synchronized E peek() {
    int     len = size();

    if (len == 0)
        throw new EmptyStackException();
    return elementAt(len - 1);
}
```

- 사이즈 검사가 없더라도 `ArrayIndexOutOfBoundsException` 가 떨어지지 만 상황에 어울리지 않기 때문에 앞선 검사가 필요하다. 

### 실패 가능성이 있는 코드를 앞에 배치한다. 
- 실제 동작전 인수 유효성 검사가 불가능 한 경우 사용

```java
// java.util.TreeMap

public V put(K key, V value) {
    Entry<K,V> t = root;
    if (t == null) {
       // ClassCastException
        compare(key, key); // type (and possibly null) check

           ... 생략 ...
    }

    if (cpr != null) {
        do {
            parent = t;
            // ClassCastException
            cmp = cpr.compare(key, t.key);

           ... 생략 ...
        } while (t != null);
    }
           ... 생략 ...
}

```

- `TreeMap` 의 경우 실제 원소 추가전 추가할 위치는 찾는 과정에서(객체 상태 변경 전) 예외를(`ClassCastException`) 발생 시킨다. 

### 객체 임시 복사본을 만든다. 
- 데이터를 임시 자료구조에 저장해 작업하는게 더 빠를 때 사용하기 좋음 
- 복사한 데이터를 바탕으로 작업을 수행하기 때문에 실패하더라도 기존 객체 상태 변경은 발생하지 않는다. 

```java
// java.util.List

default void sort(Comparator<? super E> c) {
    Object[] a = this.toArray();
    Arrays.sort(a, (Comparator) c);
    ListIterator<E> i = this.listIterator();
    for (Object e : a) {
        i.next();
        i.set((E) e);
    }
}
```

### 실패 복구 코드를 만든다. 
- (디스크 기반의) 내구성을 보장해야 하는 자료구조에 쓰인다.  (자주 쓰이는 방법은 아니다.)
- 작업 도중 발생하는 실패를 가로채는 복구 코드로 작업 전 상태로 되돌린다. 

### 실패 원자성에 대한 고찰
- 동시성 : 스레드 동기화 없이 객체를 수정하면 객체 일관성이 깨진다. 예외를 잡았다고 해서 해당 객체가 유효한 상태라고 할 순 없다. 
- Error : `Error` 는 복구 할 수 없으므로 `AssertionError` 에 대해서는 실패 원자적으로 만들지 않아도 된다. 
- 비용 과 복잡도 : 실패 원자적으로 구현하기 위한 비용과 복잡도가 높다면, 매번 실패 원자적으로 만들어야 하는 것은 아니므로 다시 고민해 보자. 
- 메서드 명세 : 메서드 명세에 기술한 예외는 실패 원자젹이여야 한다. 지키지 못한다면 실패 시 객체 상태를 API 문서에 기술해야 한다. 
  - 하지만 API 문서에서 대부분이 지켜지지 않다고 ..
