### ISSUE TITLE
아이템 77. 예외를 무시하지 말라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#77]

**Comment by qlqhqo2341** [comment]
# 77. 예외를 무시하지 말라

```java
// 예외를 무시하는 의심스러운 코드
try {
    ...
} catch (SomeException ex) {
}
```
- 위처럼 예외를 무시하는 코드는 만들지 말자..
    - 빈 catch 블록은 예외가 존재하는 이유가 없어진다.
    - API 설계자가 메서드 선언에 예외를 넣는 이유가 있을 것이다.
- `FileInputStream`을 닫을 때 라거나.. 정말 무시해도 괜찮을 때도 있지만
    - 그렇다면 무시하기로한 이유를 주석을 달아두자.
    - 예외변수 이름도 ignored로 바꿔두자.
- 무시하지 않겠다면 전파하게라도 놔두자.
