### ISSUE TITLE
아이템 8. finalizer와 cleaner 사용을 피하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#8]

**Comment by luckyDaveKim** [comment]
## 두 가지의 객체 소멸자
* finalizer : Java 9에서 deprecated 됨
* cleaner : Java 9부터 생김

<BR>

## 왜 쓰면 안될까?
* finalizer
  * 실행을 예측할 수 없음
  * 느림
  * 예외가 무시됨
  * [finalizer attack](https://github.com/NMP-Study/EffectiveJava2022/blob/main/src/test/java/org/effectivejava/item08/FinalizeAttackTest.java)에 취약
* cleaner
  * 실행을 예측할 수 없음
  * 느림
    (finalzer보다 덜 위험하 덜 느리지만, 일반적으로 불필요하다.)

<BR>

## 그렇다면 대안은?
* [AutoCloseable](https://github.com/NMP-Study/EffectiveJava2022/blob/main/src/test/java/org/effectivejava/item08/AutoCloseableTest.java)
  * 인스턴스를 다 쓰고난 후 close 메서드를 호출
    (혹은, try-with-resources 사용) #9

<BR>

## 그래도 정 쓰고 싶다면?
1. 자원의 소유자가 close 메서드를 호출하지 않을 경우에 대한 안정망 역할로 씀

ThreadPoolExecutor
(java 11 부터 finalizer 안씀, 해당 메소드 body를 비웠다.)

* java 8 의 ThreadPoolExecutor.finalize()
```java
    protected void finalize() {
        SecurityManager sm = System.getSecurityManager();
        if (sm == null || acc == null) {
            shutdown();
        } else {
            PrivilegedAction<Void> pa = () -> { shutdown(); return null; };
            AccessController.doPrivileged(pa, acc);
        }
    }
```

* java 17 의 ThreadPoolExecutor.finalize()
```java
    // Override without "throws Throwable" for compatibility with subclasses
    // whose finalize method invokes super.finalize() (as is recommended).
    // Before JDK 11, finalize() had a non-empty method body.

    /**
     * @implNote Previous versions of this class had a finalize method
     * that shut down this executor, but in this version, finalize
     * does nothing.
     */
    @Deprecated(since="9")
    protected void finalize() {}
```

FileInputStream, FileOutputStream

* java 8 의 FileInputStream.finalize()
```java
    protected void finalize() throws IOException {
        if ((fd != null) &&  (fd != FileDescriptor.in)) {
            /* if fd is shared, the references in FileDescriptor
             * will ensure that finalizer is only called when
             * safe to do so. All references using the fd have
             * become unreachable. We can call close()
             */
            close();
        }
    }
```

* java 17 의 FileInputStream.finalize() 는 메소드 자체를 지움

2. Native peer와 연결된 객체 회수
단, 성능 저하를 성능 저하를 감당할 수 있어야하고, 자원을 즉시 회수하지 않아도 되는 경우 사용해야 함

> Native method : 
> 네이티브 메소드는 C, C++ 와 같은 네이티브 언어로 작성한 메소드를 말함

> Native peer : 
> 자바 객체가 네이티브 메소드를 통해 기능수행을 위임한 것
> 예를 들어 JFrame은 Java peer이다. 그러나 실제로 그래픽을 그릴 때, 플랫폼 의존적인 네이티브 피어가 필요하다.
> 이러한 네이티브 피어는 GC가 관여할 수 없기 때문에, dispose() 등의 명시적인 자원 회수 요청을 해야한다.
