### ISSUE TITLE
아이템 81. wait와 notify보다는 동시성 유틸리티를 애용하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#81]

**Comment by luckyDaveKim** [comment]
## wait와 notify는 올바르게 사용하기가 아주 까다로우니 고수준 동시선 유틸리티를 사용하자.

java.util.concurrent 세가지 범주
- 실행자 프레임워크
- 동시성 컬렉션 (concurrent collection)
- 동기화 장치 (synchronizer)



### 동시성 컬렉션
- List, Map, Queue 같은 표준 컬렉션 인터페이스에 동시성을 가미해 구현한 고성능 컬렉션
- 동시성 컬렉션에서 동시성을 무력화하는 건 불가능
- 외부에서 락을 추가로 사용하면 오히려 속도가 느려짐


#### Map
`Collection.synchronizedMap` 보다는 `ConcurrentHashMap` 사용하자

ConcurrentMap 으로 구현한 동시성 정규화 맵
```java
private static final ConcurrnetHashMap<String, String> map = new ConcurrentHashMap<>()

public static String intern(String s){
    String previousValue = map.putIfAbsent(s, s);
    return previousValue == null ? s : previousValue;
}
```

ConcurrentMap 으로 구현한 동시성 정규화 맵 - 더 빠름
(ConcurrentHashMap은 get에 최적화 되어 있음 활용)
```java
public static String intern(String s){
    String result = map.get(s);
    if(result == null){
    	result = map.putIfAbsent(s, s);
        if (result == null)
            result = s;
    }
    return result;
}
```


#### Queue
`BlockingQueue`의 take는 큐의 첫 원소를 꺼내며, 큐가 비어있다면 새로운 원소가 추가될 때까지 기다림
ThreadPoolExecutor를 포함한 대부분의 실행자 서비스 구현체에서 사용



### 동기화 장치

CountDownLatch 로 구현한 동시 실행 시간 재기
```java
public static long time(Executor executor, int concurrency, Runnable action) throws InterruptedException {
    CountDownLatch ready = new CountDownLatch(concurrency);
    CountDownLatch start = new CountDownLatch(1);
    CountDownLatch done = new CountDownLatch(concurrency);

    for (int i = 0; i < concurrency; i++) {
        executor.execute(() -> {
            ready.countDown();
            try {
                start.await();
                action.run();
            }  catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            } finally {
                done.countDown();
            }
        });
    }

    ready.await();
    long startNanos = System.nanoTime();
    start.countDown();
    done.await();
    return System.nanoTime() - startNanos;
}
```

- time 메서드에 넘겨진 executor는 concurrency 매개변수로 지정한 동시성 수준만큼의 스레드를 생성할 수 있어야 한다. 그렇지 않으면 thread 기아 교착상태 (thread starvation deadlock)에 빠짐
- 시간 간격을 잴 때는 항상 `System.currentTimeMillis`가 아닌 정확하고 정밀한 `System.nanoTime`을 사용하자

**Comment by luckyDaveKim** [comment]
자주 쓰이는 동기화 장치 
- CountDownLatch
- Semaphore
- CyclicBarrier
- Exchanger
- Phaser

궁금하면 좀 더 찾아보자~
