### ISSUE TITLE
아이템 82. 스레드 안전성 수준을 문서화하라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#82]

**Comment by bluewbear** [comment]
## item 82 : 스레드 안전성 수준을 문서화하라

- 한 메서드를 여러 스레드가 동시 호출할때
  - 메서드가 어떻게 동작하느냐는 해당 클래스와 이를 사용하는 클라이언트 사이의 중요한 계약!
- `synchronized` 한정자 있는 메서드는 안전하다?
  - **javadoc 기본 옵션에서 생성한 API 문서에는 `synchronized` 한정자가 포함하지 않는다.**
    - 메서드 선언에 synchronized 한정자를 선언할지는 구현 이슈이지 API에는 속하지 않는다.
- **멀티 스레드 환경에서도 API를 안전하게 사용하려면 클래스가 지원하는 스레드 안정선 수준을 정확히 명시해야함**
- 완벽하진 않지만 일반적으로 스레드 안전성이 보장이 잘되는 수준의 순서
  - **불변**(immutable)
    - 마치 상수와 같아 외부 동기화 불필요
    - ex) `String`, `Long`, `BigInterger`
  - **무조건적 스레드 안전**(unconditionally thread-safe)
    - 클래스의 인스턴스는 수정될 수 있으나, 내부에서 충실히 동기화하여 별도의 외부 동기화 불필요
    - ex) `AtomicLong`, `ConcurrentHashMap`
  - **조건부 스레드 안전**(conditionally thread-safe)
    - 무조건적 스레드 안전과 같으나 일부 메서드를 사용하려면 외부 동기화가 필요한 경우
    - ex) `Collections.synchronized` wrapper 메서드가 반환한 컬렉션들 
    - <img width="400" alt="스크린샷 2023-03-29 오전 3 18 25" src="https://user-images.githubusercontent.com/18572514/228331331-aa41361e-c7d1-40e7-9424-8feaad11c337.png">
  - **스레드 안전하지 않음**(not thread-safe)
    - 클래스의 인스턴스는 수정될 수 있다. 동시 사용하려면 각각의 메소드 호출을 클라이언트가 선택한 외부 동기화 메커니즘으로 감싸야한다.
    - ex) `ArrayList`, `HashMap` 같은 기본 컬렉션들 
  - **스레드 적대적**(thread-hostile)
    - 모든 메서드 호출을 외부 동기화로 감싸도 멀티스레드 환경에서 안전하지 않다.
    - ex) item78의 generateSerialNumber 메서드에서 내부 동기화 생략하면..
    - ```java
       private static volatile int nextSerialNumber = 0;

       public static int generateSerialNumber() {
           return nextSerialNumber++;
       }
       // 일련번호 생성 코드 
       ```
- "자바 병렬 프로그래밍" 부록 A [yes24 출처](http://www.yes24.com/Product/Goods/3015162)
  - <img width="300" alt="스크린샷 2023-03-29 오전 2 46 38" src="https://user-images.githubusercontent.com/18572514/228324550-b0da6a4e-c1b3-4117-9409-955de0380379.png">
  - [병렬 프로그램을 위한 annotation](https://aroundck.tistory.com/3423)
    - `@Immutable`
      - 불변 클래스, 자동으로 `@ThreadSafe`
    - `@ThreadSafe`
      - 무조건적/조건적 스레드 안전이 여기에 속함
    - `@NotThreadSafe`
      - `@Immutable`, `@ThreadSafe` 등 스레드 안정성을 확보했다는 annotation을 달지 않으면 당연하게 `@NotThreadSafe`
- 조건부 스레드 안전의 경우 주의해서 문서화 해야한다.
  - 어떤 순서로 호출할때 외부 동기화가 필요한지, 그 순서로 호출할려면 어떤 락을 얻어야하는지 명시 
    - [Collections.synchronizedMap API javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#synchronizedMap-java.util.Map-)
    - synchronizedMap이 반환한 맵의 컵렉션 뷰를 순회하려면 반드시 그 맵을 락으로 사용해서 수동으로 동기화
    - <img width="400" alt="스크린샷 2023-03-29 오전 2 59 07" src="https://user-images.githubusercontent.com/18572514/228327354-8ab427da-c8df-46dd-8ef7-45717ed69dde.png">
- 클래스의 스레드 안전성은 보통 클래스의 문서화 주석 영역에 기재하지만,
  - 톡특한 특성의 메서드라면 메서드의 주석에 기재
  - ex) `Collections.synchronizedMap` 가 좋은 예 
- 클래스 외부에서 사용할 수 있는 락을 제공하면..
  - 클라이언트에서 일련의 메서드 호출을 원자적으로 수행할 수 있으나..
  - 대가가 따른다.
  - 내부에서 처리하는 고성능 동시성 제어 메커니즘과 혼용할 수 없다. ConcurrentHashMap 같은 동시성 컬렉션을 같이 사용 못한다.
  - 클라이언트가 락을 쥐고 놓지 않는 서비스 거부 공격(denial-of-service-attack)을 수행할  가능성도 존재 
  - 비공개 락 객체를 사용 권장 
  - ```java
     private final Object lock = new Object; // 항상 final로 선언할 것 
     public void foo() {
         synchronized(lock) {
             ...
         }
     }
     ```
  - [item 15 : 클래스와 멤버의 접근 권한을 최소화하라](https://github.com/NMP-Study/EffectiveJava2022/issues/15) 조언 내용 
  - 비공개 락은 "무조건적 스레드 안정" 클래스에서만 사용 가능 


> 핵심 정리
> 모든 클래스가 자신의 스레드 안전성 정보를 명확히 문서화해야 한다.
