### ISSUE TITLE
아이템 85. 자바 직렬화의 대안을 찾으라

### ISSUE THREAD

**Issue by okhee** [NMP-Study/EffectiveJava2022#85]

**Comment by qlqhqo2341** [comment]
# 직렬화의 대안을 찾으라

### 직렬화가 위험한 이유
- 어플리케이션을 아무리 잘만들어도 역직렬화 보안문제를 방어하기 어려움
    - 바이트 스트림을 역직렬화 하는 과정에서 그 타입의 모든 코드를 수행할 수 있기 때문.
    - 역직렬화 과정에서 잠재적 위험을 지닌 메소드를 **가젯**이라 하며, 
      여러 가젯을 엮어서 **가젯 체인**을 만들기도 함.

#### 역직렬화 폭탄
- 가젯도 필요없이 역직렬화에 시간을 엄청 오래걸리게 하여 공격할 수도 있음. 
```java
static byte[] bomb() {
    Set<Object> root = new HashSet<>();
    Set<Object> s1 = root;
    Set<Object> s2 = new HashSet<>();
    for (int i = 0; i < 100; i++) {
        Set<Object> t1 = new HashSet();
        Set<Object> t2 = new HashSet();
        t1.add("foo"); // t1을 t2와 다르게 만든다.
        s1.add(t1); s1.add(t2);
        s2.add(t1); s2.add(t2);
        s1 = t1;
        s2 = t2;
    }
    return serialize(root);
}
```
- set이 만들어지는 전체 갯수는 약 201개, set의 깊이가 약 100개 까지됨., 역직렬화를 하면서 hashCode 메서드를 2^100 번 넘게 호출하게된다.
  => 역직렬화가 끝나지 않음..
  => 서비스 거부 공격(DoS) 등에 사용 될 수 있음.
  
### 직렬화의 대안 - 크로스-플랫폼 구조화된 데이터 표현
- 간단히 속성-값 쌍의 집합으로 구성된 구조화된 데이터
- json
    - 텍스트 기반으로 읽기가 쉬움
    - 원래 javascript 에서 쓰임
- protobuf
    - 2진 표현으로 데이터 효율이 좋음
    - 원래 C++용이었음

### 레거시 시스템 떄문에 직렬화를 정말로 써야한다면
- 신뢰할 수 없는 데이터는 절대 역직렬화 하지 말자.
- 역직렬화 필터링(java.io.ObjectInputFilter)을 사용하자
    - 역직렬화할 클래스를 블랙리스트나 화이트리스트로 지정할 수 있음.
    - 물론 화이트리스트를 추천
    - 역직렬화 폭탄 같은 것은 물론 못막음.

### 결론
- 직렬화는 쓰지 말자
- 부득이 쓸거면 정말로 신경써서 만들어야함. (다음 아이템 부터 나올 내용)
