### ISSUE TITLE
책 추천!! 

### ISSUE THREAD

**Issue by RulLu16** [NMP-Study/EffectiveJava2022#91]
### 개발 서적 추천 목록 (feat. 초록창 스터디 도서 지원비)
- 동료들에게 **추천**하고 싶거나 **관심있는** 개발 서적을 아래 댓글에 추가해주세요!
- 각 댓글에 👍으로 책에 대한 관심도를 표현해보세요!

**Comment by okhee** [comment]
## [오브젝트(객체지향 설계 이야기)](http://www.yes24.com/Product/Goods/74219491) - 민규님
<img height="260" src="https://user-images.githubusercontent.com/5165217/203472092-473114cd-14df-48e9-a6ac-2e16e5786cf4.png" />

**Comment by okhee** [comment]
## [클린코드](https://product.kyobobook.co.kr/detail/S000001032980) - 민규님
<img height="260" src="https://user-images.githubusercontent.com/5165217/203472319-59e78be5-9dae-4b4b-8c21-dd7719dc9de2.png" />

**Comment by okhee** [comment]
## [테스트 주도 개발](http://www.yes24.com/Product/Goods/12246033) - 민규님
<img height="260" src="https://user-images.githubusercontent.com/5165217/203472450-d9fedc6a-1a09-458b-acae-5f639d820be5.png" />

**Comment by okhee** [comment]
## [데이터중심 어플리케이션 설계](http://www.yes24.com/Product/Goods/59566585) - 정한님
<img height="260" src="https://user-images.githubusercontent.com/5165217/203472561-81a15ef4-48ef-4408-9b67-44deacea1a02.png" />

**Comment by okhee** [comment]
## [아파치 카프카 애플리케이션 프로그래밍 with 자바](http://www.yes24.com/Product/Goods/99122569) - 예은님
<img height="260" src="https://user-images.githubusercontent.com/5165217/203472633-4a7cb825-b2ea-4f28-b855-2db35debe475.png" />

**Comment by okhee** [comment]
## [모던 자바스크립트 deep dive](http://www.yes24.com/Product/Goods/92742567) - 예은님
<img height="260" src="https://user-images.githubusercontent.com/5165217/203472690-2e247444-49c1-4037-bd40-8ac4a4791a5d.png" />

**Comment by okhee** [comment]
## [Real MySQL 8.0 Vol.1](http://www.yes24.com/Product/Goods/103415627) - 윤상님
<img height="260" src="https://user-images.githubusercontent.com/5165217/203472774-af0074af-b0d8-4840-9c8d-3a7345ded150.png" />

**Comment by qlqhqo2341** [comment]
## [실용주의 프로그래머](http://www.yes24.com/Product/Goods/107077663) - 정한님
<img height="260" src="https://user-images.githubusercontent.com/10750050/203474946-817f4289-6dde-415b-b239-6f131e848053.png" />

**Comment by qlqhqo2341** [comment]
## [이펙티브 타입스크립트](http://www.yes24.com/Product/Goods/102124327) - 정한님
<img height="260" src="https://user-images.githubusercontent.com/10750050/203475240-d92d1cd4-f6a9-4745-9c63-60e07a6172e8.png" />

**Comment by bluewbear** [comment]
## [소프트웨어 아키텍처 101](http://www.yes24.com/product/goods/104491433) - 서원쓰
<img height="260" alt="스크린샷 2022-11-24 오전 1 59 49" src="https://user-images.githubusercontent.com/18572514/203605732-dcc5754f-ff28-4421-95f9-4ef65bb7bd2e.png">

**Comment by bluewbear** [comment]
## [러닝 Go](http://www.yes24.com/Product/Goods/107680603) - 서원쓰
<img height="260" alt="스크린샷 2022-11-24 오전 2 09 03" src="https://user-images.githubusercontent.com/18572514/203607509-152c679c-fd65-430b-aad8-0385afc2b941.png">

**Comment by okhee** [comment]
## [토비의 스프링 3.1 Vol. 1 스프링의 이해와 원리](http://www.yes24.com/Product/Goods/7516721) - 태완님
<img height="260" src="https://user-images.githubusercontent.com/5165217/203731616-25837fa1-e2f1-4701-b4a5-a8841ec6e4e4.png">

**Comment by okhee** [comment]
## [모던 자바 인 액션](http://www.yes24.com/Product/Goods/77125987) - 정원님
<img height="260" src="https://user-images.githubusercontent.com/5165217/203731829-3064aa2e-c554-44fc-b82f-e8405ccd32f9.png">

**Comment by windowforsun** [comment]
## [스프링 부트로 개발하는 MSA 컴포넌트](https://product.kyobobook.co.kr/detail/S000200221921) - 창선님

<img height="260" src="https://user-images.githubusercontent.com/33018854/204542241-52c93954-83b9-493b-ac05-2486688cb6ec.png">

**Comment by windowforsun** [comment]
## [카프카, 데이터 플랫폼의 최강자](http://www.yes24.com/Product/Goods/59789254) - 창선님

<img height="260" src="https://user-images.githubusercontent.com/33018854/204542807-d24cf4f3-5bf6-4b25-8f59-7d005212ce00.png">
